
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - core.kubecarrier.io
  resources:
  - crdreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubecarrier.io
  resources:
  - crdreferences/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubecarrier.io
  resources:
  - serviceclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubecarrier.io
  resources:
  - serviceclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubecarrier.io
  resources:
  - tenantassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubecarrier.io
  resources:
  - tenantassignments/status
  verbs:
  - get
  - patch
  - update
