---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubecarrier:service-cluster-admin-e2e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubecarrier:e2e-clusterrole
subjects:
  - kind: ServiceAccount
    name: kubecarrier
    namespace: default
