project_name: kubecarrier
before:
release:
  github:
    owner: kubermatic
    name: kubecarrier
  prerelease: true
builds:
  - &build-cli
    id: kubecarrier
    binary: kubecarrier
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/kubectl-kubecarrier/main.go
    ldflags: >
      -s -w
      -X github.com/kubermatic/kubecarrier/pkg/internal/version.Version={{.Tag}}
      -X github.com/kubermatic/kubecarrier/pkg/internal/version.Branch={{.Tag}}
      -X github.com/kubermatic/kubecarrier/pkg/internal/version.Commit={{.ShortCommit}}
      -X github.com/kubermatic/kubecarrier/pkg/internal/version.BuildDate={{.Timestamp}}
  - &build
    <<: *build-cli
    id: manager
    binary: manager
    goos:
      - linux
    goarch:
      - amd64
    main: cmd/manager/main.go
  - <<: *build
    id: operator
    binary: operator
    main: cmd/operator/main.go
  - <<: *build
    id: catapult
    binary: catapult
    main: cmd/catapult/main.go
  - <<: *build
    id: ferry
    binary: ferry
    main: cmd/ferry/main.go
  - <<: *build
    id: elevator
    binary: elevator
    main: cmd/elevator/main.go
  - <<: *build
    id: api-server
    binary: api-server
    main: cmd/apiserver/main.go
archives:
  - id: kubecarrier
    builds:
      - kubecarrier
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
dockers:
- &docker
  goos: linux
  goarch: amd64
  binaries:
    - manager
  builds:
    - manager
  image_templates:
    - "quay.io/kubecarrier/manager:latest"
    - "quay.io/kubecarrier/manager:{{ .Tag }}"
    - "quay.io/kubecarrier/manager:v{{ .Major }}"
  dockerfile: config/dockerfiles/manager.Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- <<: *docker
  binaries:
    - operator
  builds:
    - operator
  image_templates:
    - "quay.io/kubecarrier/operator:latest"
    - "quay.io/kubecarrier/operator:{{ .Tag }}"
    - "quay.io/kubecarrier/operator:v{{ .Major }}"
  dockerfile: config/dockerfiles/operator.Dockerfile
- <<: *docker
  binaries:
    - catapult
  builds:
    - catapult
  image_templates:
    - "quay.io/kubecarrier/catapult:latest"
    - "quay.io/kubecarrier/catapult:{{ .Tag }}"
    - "quay.io/kubecarrier/catapult:v{{ .Major }}"
  dockerfile: config/dockerfiles/catapult.Dockerfile
- <<: *docker
  binaries:
    - ferry
  builds:
    - ferry
  image_templates:
    - "quay.io/kubecarrier/ferry:latest"
    - "quay.io/kubecarrier/ferry:{{ .Tag }}"
    - "quay.io/kubecarrier/ferry:v{{ .Major }}"
  dockerfile: config/dockerfiles/ferry.Dockerfile
- <<: *docker
  binaries:
    - elevator
  builds:
    - elevator
  image_templates:
    - "quay.io/kubecarrier/elevator:latest"
    - "quay.io/kubecarrier/elevator:{{ .Tag }}"
    - "quay.io/kubecarrier/elevator:v{{ .Major }}"
  dockerfile: config/dockerfiles/elevator.Dockerfile
- <<: *docker
  binaries:
    - apiserver
  builds:
    - apiserver
  image_templates:
    - "quay.io/kubecarrier/apiserver:latest"
    - "quay.io/kubecarrier/apiserver:{{ .Tag }}"
    - "quay.io/kubecarrier/apiserver:v{{ .Major }}"
  dockerfile: config/dockerfiles/apiserver.Dockerfile
