exclude: "vendor/ | *.deepcopy.go"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
    exclude: "config/swagger/.*"
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: pretty-format-json
    args:
    - --autofix
  - id: trailing-whitespace
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
  - id: go-fmt
- repo: local
  hooks:
  - id: goimports
    name: goimports
    entry: goimports -local github.com/kubermatic -w
    language: system
    types: [go]
  - id: LICENSE
    name: LICENSE
    language: system
    entry: bash ./hack/verify-boilerplate.sh
    exclude: ".*"
    always_run: true
  - id: go-mod-tidy
    name: go-mod-tidy
    entry: make tidy
    language: system
    exclude: ".*"
    always_run: true
