presubmits:
  kubermatic/kubecarrier:
    - name: pull-kubermatic-kubecarrier-validate-prow-yaml
      always_run: true
      decorate: true
      clone_uri: ssh://git@github.com/kubermatic/kubecarrier.git
      extra_refs:
        - org: kubermatic
          repo: infra
          base_ref: master
          clone_uri: git@github.com:kubermatic/infra.git
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20200203-711d3732b
            command:
              - /app/prow/cmd/checkconfig/app.binary
            args:
              - --plugin-config=/home/prow/go/src/github.com/kubermatic/infra/prow/plugins.yaml
              - --config-path=/home/prow/go/src/github.com/kubermatic/infra/prow/config.yaml
              - --job-config-path=/home/prow/go/src/github.com/kubermatic/infra/prow/jobs
              - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)

    - name: pull-kubecarrier-test
      always_run: true
      decorate: true
      clone_uri: ssh://git@github.com/kubermatic/kubecarrier.git
      spec:
        containers:
          - image: quay.io/kubecarrier/test
            imagePullPolicy: Always
            command:
              - make
              - test
            env:
              - name: GO111MODULE
                value: 'on'
            resources:
              requests:
                cpu: 800m
    - name: pull-kubecarrier-lint
      always_run: true
      decorate: true
      clone_uri: ssh://git@github.com/kubermatic/kubecarrier.git
      spec:
        containers:
          - image: quay.io/kubecarrier/test
            imagePullPolicy: Always
            command:
              - make
              - lint
            env:
              - name: GO111MODULE
                value: 'on'
            resources:
              requests:
                cpu: 800m
                memory: 4Gi
    - name: pull-kubecarrier-e2e-v1.17.0
      always_run: true
      decorate: true
      clone_uri: ssh://git@github.com/kubermatic/kubecarrier.git
      spec:
        # DNS configuration allows inner cluster to access the internet.
        dnsPolicy: "None"
        dnsConfig:
          nameservers:
            - 1.1.1.1 # Cloudflare DNS servers
            - 1.0.0.1
        containers:
          - image: quay.io/kubecarrier/test
            imagePullPolicy: Always
            name: e2e-test
            command:
              - make
              - e2e-test
            env:
              - name: GO111MODULE
                value: 'on'
              - name: KIND_NODE_IMAGE
                value: "kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62"
            volumeMounts:
              - name: modules
                mountPath: /lib/modules
              - name: cgroup
                mountPath: /sys/fs/cgroup
            # docker-in-docker needs privileged mode
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 800m
                memory: 2Gi
        # Those volumes are required by inner docker instance to properly start the k8s cluster inside the pod.
        volumes:
          - name: modules
            hostPath:
              path: /lib/modules
              type: Directory
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
              type: Directory
    - name: pull-kubecarrier-e2e-v1.16.4
      always_run: true
      decorate: true
      clone_uri: ssh://git@github.com/kubermatic/kubecarrier.git
      spec:
        # DNS configuration allows inner cluster to access the internet.
        dnsPolicy: "None"
        dnsConfig:
          nameservers:
            - 1.1.1.1 # Cloudflare DNS servers
            - 1.0.0.1
        containers:
          - image: quay.io/kubecarrier/test
            imagePullPolicy: Always
            name: e2e-test
            command:
              - make
              - e2e-test
            env:
              - name: GO111MODULE
                value: 'on'
              - name: KIND_NODE_IMAGE
                value: "kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55"
            volumeMounts:
              - name: modules
                mountPath: /lib/modules
              - name: cgroup
                mountPath: /sys/fs/cgroup
            # docker-in-docker needs privileged mode
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 800m
                memory: 2Gi
        # Those volumes are required by inner docker instance to properly start the k8s cluster inside the pod.
        volumes:
          - name: modules
            hostPath:
              path: /lib/modules
              type: Directory
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
              type: Directory
#postsubmits:
#  kubermatic/kubecarrier:
#    - name: post-kubecarrier-test-image
#      decorate: true
#      clone_uri: ssh://git@github.com/kubermatic/kubecarrier.git
#      branches:
#        - ^master$
#      run_if_changed: "(go.sum|go.mod|start-docker.sh|test.Dockerfile|.pre-commit-config.yaml)"
#      spec:
#        containers:
#          - image: quay.io/kubecarrier/test
#            imagePullPolicy: Always
#            name: e2e-test
#            command:
#              - make
#              - push-image-test
#            env:
#              - name: GO111MODULE
#                value: 'on'
#              - name: QUAY_IO_USERNAME
#                valueFrom:
#                  secretKeyRef:
#                    name: kubecarrier-quay.io
#                    key: username
#              - name: QUAY_IO_PASSWORD
#                valueFrom:
#                  secretKeyRef:
#                    name: kubecarrier-quay.io
#                    key: password
#            # docker needs privileged mode
#            securityContext:
#              privileged: true
#            resources:
#              requests:
#                cpu: 800m
#                memory: 2Gi
