
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager
rules:
- apiGroups:
  - catalog.kubecarrier.io
  resources:
  - derivedcustomresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubecarrier.io
  resources:
  - derivedcustomresources/status
  verbs:
  - get
