
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fake.kubecarrier.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fake.kubecarrier.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fake.kubecarrier.io
  resources:
  - dbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fake.kubecarrier.io
  resources:
  - dbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fake.kubecarrier.io
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fake.kubecarrier.io
  resources:
  - snapshots/status
  verbs:
  - get
  - patch
  - update
