---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: agg-manager-role
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        "kubecarrier.io/manager": "true"
    - matchLabels:
        "kubecarrier.io/role": "manager"
rules: []
