
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - catalog.kubecarrier.io
  resources:
  - offerings
  verbs:
  - get
  - list
- apiGroups:
  - catalog.kubecarrier.io
  resources:
  - providers
  verbs:
  - get
  - list
- apiGroups:
  - catalog.kubecarrier.io
  resources:
  - regions
  verbs:
  - get
  - list
