
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager
rules:
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusterassignments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusterassignments/status
  verbs:
  - get
