# https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # ignore pod log requests
  - level: None
    resources:
    - group: ""
      resources:
      - "pods/log"
      - "pods/status"
  # ignore all kube-system namespace originating requests
  - level: None
    namespaces:
    - "kube-system"
  - level: Metadata
