
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager
rules:
- apiGroups:
  - kubecarrier.io
  resources:
  - customresourcedefinitiondiscoveries
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecarrier.io
  resources:
  - customresourcedefinitiondiscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusterassignments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusterassignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kubecarrier.io
  resources:
  - serviceclusterregistrations
  verbs:
  - get
  - list
  - watch
