
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubecarrier.io
  resources:
  - customresourcedefinitiondiscoveries
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecarrier.io
  resources:
  - customresourcedefinitiondiscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecarrier.io
  resources:
  - serviceclusters/status
  verbs:
  - get
  - patch
  - update
