
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - master.kubecarrier.io
  resources:
  - managementclusters
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - master.kubecarrier.io
  resources:
  - managementclusters/status
  verbs:
  - get
  - patch
  - update
