/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kubecarrier.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Types
type APIVersion struct {
	Version              string               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Branch               string               `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	BuildDate            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	GoVersion            string               `protobuf:"bytes,4,opt,name=goVersion,proto3" json:"goVersion,omitempty"`
	Platform             string               `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *APIVersion) Reset()         { *m = APIVersion{} }
func (m *APIVersion) String() string { return proto.CompactTextString(m) }
func (*APIVersion) ProtoMessage()    {}
func (*APIVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_046afb50055b7632, []int{0}
}

func (m *APIVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIVersion.Unmarshal(m, b)
}
func (m *APIVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIVersion.Marshal(b, m, deterministic)
}
func (m *APIVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIVersion.Merge(m, src)
}
func (m *APIVersion) XXX_Size() int {
	return xxx_messageInfo_APIVersion.Size(m)
}
func (m *APIVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_APIVersion.DiscardUnknown(m)
}

var xxx_messageInfo_APIVersion proto.InternalMessageInfo

func (m *APIVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *APIVersion) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *APIVersion) GetBuildDate() *timestamp.Timestamp {
	if m != nil {
		return m.BuildDate
	}
	return nil
}

func (m *APIVersion) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *APIVersion) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

// Requests/Responses
type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_046afb50055b7632, []int{1}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type UserInfo struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Groups               []string `protobuf:"bytes,2,rep,name=Groups,proto3" json:"Groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_046afb50055b7632, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserInfo) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterType((*APIVersion)(nil), "kubecarrier.api.v1alpha1.APIVersion")
	proto.RegisterType((*VersionRequest)(nil), "kubecarrier.api.v1alpha1.VersionRequest")
	proto.RegisterType((*UserInfo)(nil), "kubecarrier.api.v1alpha1.UserInfo")
}

func init() { proto.RegisterFile("kubecarrier.proto", fileDescriptor_046afb50055b7632) }

var fileDescriptor_046afb50055b7632 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xdf, 0x4a, 0xfb, 0x30,
	0x18, 0xa5, 0xdb, 0x7e, 0xdb, 0xfa, 0x0d, 0x7e, 0xba, 0x08, 0x23, 0xd6, 0x81, 0xa3, 0x78, 0xb1,
	0xab, 0x96, 0x4d, 0x10, 0x6f, 0x27, 0x8a, 0x0c, 0x6f, 0x64, 0x38, 0x05, 0xef, 0xd2, 0x99, 0xad,
	0xc1, 0xb6, 0x89, 0x69, 0x3a, 0xf1, 0xd6, 0x57, 0xf0, 0x4d, 0x7c, 0x15, 0xef, 0xbc, 0xf6, 0x41,
	0xa4, 0x69, 0x63, 0xfd, 0xc3, 0xee, 0xbe, 0x93, 0x73, 0x92, 0x73, 0x72, 0x3e, 0xe8, 0xde, 0x67,
	0x01, 0x5d, 0x10, 0x29, 0x19, 0x95, 0x9e, 0x90, 0x5c, 0x71, 0x84, 0xbf, 0x1f, 0x11, 0xc1, 0xbc,
	0xf5, 0x88, 0x44, 0x22, 0x24, 0x23, 0x67, 0x7f, 0xc5, 0xf9, 0x2a, 0xa2, 0xbe, 0xd6, 0x05, 0xd9,
	0xd2, 0x57, 0x2c, 0xa6, 0xa9, 0x22, 0xb1, 0x28, 0xae, 0x3a, 0x7b, 0xbf, 0x05, 0x34, 0x16, 0xea,
	0xa9, 0x24, 0xfb, 0x25, 0x49, 0x04, 0xf3, 0x49, 0x92, 0x70, 0x45, 0x14, 0xe3, 0x49, 0x5a, 0xb0,
	0xee, 0xab, 0x05, 0x30, 0xb9, 0x9c, 0x5e, 0x53, 0x99, 0x32, 0x9e, 0x20, 0x0c, 0xad, 0x75, 0x31,
	0x62, 0x6b, 0x60, 0x0d, 0xed, 0x99, 0x81, 0xa8, 0x07, 0xcd, 0x40, 0x92, 0x64, 0x11, 0xe2, 0x9a,
	0x26, 0x4a, 0x84, 0x8e, 0xc1, 0x0e, 0x32, 0x16, 0xdd, 0x9d, 0x12, 0x45, 0x71, 0x7d, 0x60, 0x0d,
	0x3b, 0x63, 0xc7, 0x2b, 0x2c, 0x3d, 0x93, 0xc7, 0xbb, 0x32, 0x81, 0x67, 0x95, 0x18, 0xf5, 0xc1,
	0x5e, 0xf1, 0xd2, 0x18, 0x37, 0xf4, 0xa3, 0xd5, 0x01, 0x72, 0xa0, 0x2d, 0x22, 0xa2, 0x96, 0x5c,
	0xc6, 0xf8, 0x9f, 0x26, 0xbf, 0xb0, 0xbb, 0x0d, 0xff, 0x4b, 0xd9, 0x8c, 0x3e, 0x64, 0x34, 0x55,
	0xee, 0x11, 0xb4, 0xe7, 0x29, 0x95, 0xd3, 0x64, 0xc9, 0x11, 0x82, 0x46, 0x3e, 0x97, 0x1f, 0xd0,
	0x73, 0x9e, 0xfe, 0x5c, 0xf2, 0x4c, 0xa4, 0xb8, 0x36, 0xa8, 0xe7, 0xe9, 0x0b, 0x34, 0x7e, 0xb7,
	0xa0, 0x73, 0x51, 0xf5, 0x8e, 0x14, 0xb4, 0x4c, 0x80, 0xa1, 0xb7, 0x69, 0x21, 0xde, 0x4f, 0x73,
	0xe7, 0x60, 0xb3, 0xb2, 0xaa, 0xd6, 0xdd, 0x7d, 0x7e, 0xfb, 0x78, 0xa9, 0xed, 0xa0, 0xae, 0x6f,
	0x58, 0xdf, 0x74, 0x3b, 0x87, 0xe6, 0x4d, 0xc8, 0x27, 0xf1, 0x14, 0xf5, 0xfe, 0x54, 0x77, 0x96,
	0xaf, 0xd2, 0x71, 0x37, 0x5b, 0x98, 0x7f, 0xbb, 0x5b, 0xda, 0xc0, 0x46, 0x2d, 0xff, 0x31, 0xe4,
	0x24, 0x66, 0x27, 0x70, 0xdb, 0x36, 0xaa, 0xa0, 0xa9, 0x1f, 0x3c, 0xfc, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xe7, 0xc4, 0xf9, 0x0b, 0x79, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KubecarrierClient is the client API for Kubecarrier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KubecarrierClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*APIVersion, error)
	WhoAmI(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserInfo, error)
}

type kubecarrierClient struct {
	cc *grpc.ClientConn
}

func NewKubecarrierClient(cc *grpc.ClientConn) KubecarrierClient {
	return &kubecarrierClient{cc}
}

func (c *kubecarrierClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*APIVersion, error) {
	out := new(APIVersion)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1alpha1.Kubecarrier/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubecarrierClient) WhoAmI(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1alpha1.Kubecarrier/WhoAmI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubecarrierServer is the server API for Kubecarrier service.
type KubecarrierServer interface {
	Version(context.Context, *VersionRequest) (*APIVersion, error)
	WhoAmI(context.Context, *empty.Empty) (*UserInfo, error)
}

func RegisterKubecarrierServer(s *grpc.Server, srv KubecarrierServer) {
	s.RegisterService(&_Kubecarrier_serviceDesc, srv)
}

func _Kubecarrier_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubecarrierServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1alpha1.Kubecarrier/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubecarrierServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubecarrier_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubecarrierServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1alpha1.Kubecarrier/WhoAmI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubecarrierServer).WhoAmI(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kubecarrier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1alpha1.Kubecarrier",
	HandlerType: (*KubecarrierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Kubecarrier_Version_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _Kubecarrier_WhoAmI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kubecarrier.proto",
}
