/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: version.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Types
type APIVersion struct {
	Version              string               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Branch               string               `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	BuildDate            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	GoVersion            string               `protobuf:"bytes,4,opt,name=goVersion,proto3" json:"goVersion,omitempty"`
	Platform             string               `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *APIVersion) Reset()         { *m = APIVersion{} }
func (m *APIVersion) String() string { return proto.CompactTextString(m) }
func (*APIVersion) ProtoMessage()    {}
func (*APIVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{0}
}

func (m *APIVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIVersion.Unmarshal(m, b)
}
func (m *APIVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIVersion.Marshal(b, m, deterministic)
}
func (m *APIVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIVersion.Merge(m, src)
}
func (m *APIVersion) XXX_Size() int {
	return xxx_messageInfo_APIVersion.Size(m)
}
func (m *APIVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_APIVersion.DiscardUnknown(m)
}

var xxx_messageInfo_APIVersion proto.InternalMessageInfo

func (m *APIVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *APIVersion) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *APIVersion) GetBuildDate() *timestamp.Timestamp {
	if m != nil {
		return m.BuildDate
	}
	return nil
}

func (m *APIVersion) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *APIVersion) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

// Requests/Responses
type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{1}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*APIVersion)(nil), "kubecarrier.api.v1.APIVersion")
	proto.RegisterType((*VersionRequest)(nil), "kubecarrier.api.v1.VersionRequest")
}

func init() {
	proto.RegisterFile("version.proto", fileDescriptor_7d2c07d79758f814)
}

var fileDescriptor_7d2c07d79758f814 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0xe9, 0xfc, 0xbf, 0x33, 0xed, 0x95, 0x11, 0x89, 0x20, 0xa1, 0x0c, 0x3a, 0x74, 0x35,
	0xb8, 0x48, 0xe9, 0xb8, 0x11, 0x77, 0x8a, 0x1b, 0x77, 0x52, 0xc5, 0x85, 0xbb, 0x9b, 0x9a, 0xe9,
	0x04, 0xdb, 0x26, 0xa6, 0x69, 0x1f, 0xc0, 0x57, 0xf0, 0x4d, 0x7c, 0x15, 0x5f, 0xc1, 0x07, 0x11,
	0xda, 0x74, 0x8a, 0xe8, 0xf2, 0xde, 0xf3, 0xe5, 0x9c, 0x9b, 0x03, 0xf3, 0x56, 0x98, 0x5a, 0xaa,
	0x8a, 0x69, 0xa3, 0xac, 0x22, 0xe4, 0xa5, 0xe1, 0x22, 0x43, 0x63, 0xa4, 0x30, 0x0c, 0xb5, 0x64,
	0x6d, 0x12, 0x9e, 0xe6, 0x4a, 0xe5, 0x85, 0x88, 0x3b, 0x82, 0x37, 0x9b, 0xd8, 0xca, 0x52, 0xd4,
	0x16, 0x4b, 0xdd, 0x3f, 0x0a, 0x17, 0x0e, 0x40, 0x2d, 0x63, 0xac, 0x2a, 0x65, 0xd1, 0x4a, 0x55,
	0xd5, 0xbd, 0x1a, 0x7d, 0x78, 0x00, 0x57, 0x77, 0xb7, 0x8f, 0x7d, 0x0e, 0xa1, 0x30, 0x73, 0x91,
	0xd4, 0x5b, 0x7a, 0xab, 0x20, 0x1d, 0x46, 0x72, 0x0c, 0x53, 0x6e, 0xb0, 0xca, 0xb6, 0x74, 0xd2,
	0x09, 0x6e, 0x22, 0x17, 0x10, 0xf0, 0x46, 0x16, 0xcf, 0x37, 0x68, 0x05, 0xfd, 0xb7, 0xf4, 0x56,
	0xfb, 0xeb, 0x90, 0xf5, 0x91, 0x6c, 0xb8, 0x89, 0x3d, 0x0c, 0x37, 0xa5, 0x23, 0x4c, 0x16, 0x10,
	0xe4, 0xca, 0x05, 0xd3, 0xff, 0x9d, 0xe9, 0xb8, 0x20, 0x21, 0xf8, 0xba, 0x40, 0xbb, 0x51, 0xa6,
	0xa4, 0x7b, 0x9d, 0xb8, 0x9b, 0xa3, 0x43, 0x38, 0x70, 0x58, 0x2a, 0x5e, 0x1b, 0x51, 0xdb, 0xb5,
	0xdd, 0x6d, 0xee, 0x85, 0x69, 0x65, 0x26, 0x08, 0x87, 0xd9, 0x60, 0x15, 0xb1, 0xdf, 0xbd, 0xb1,
	0x9f, 0x06, 0xe1, 0xc9, 0x5f, 0xcc, 0x58, 0x4c, 0x74, 0xf4, 0xf6, 0xf9, 0xf5, 0x3e, 0x99, 0x47,
	0x7e, 0xec, 0x0a, 0xb9, 0xf4, 0xce, 0xae, 0xe1, 0xc9, 0x6f, 0x13, 0x2c, 0xf4, 0x16, 0x13, 0x3e,
	0xed, 0x3e, 0x7b, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x89, 0x6f, 0x6c, 0xb3, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VersionServiceClient is the client API for VersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VersionServiceClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*APIVersion, error)
}

type versionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionServiceClient(cc grpc.ClientConnInterface) VersionServiceClient {
	return &versionServiceClient{cc}
}

func (c *versionServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*APIVersion, error) {
	out := new(APIVersion)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.VersionService/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionServiceServer is the server API for VersionService service.
type VersionServiceServer interface {
	Version(context.Context, *VersionRequest) (*APIVersion, error)
}

// UnimplementedVersionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVersionServiceServer struct {
}

func (*UnimplementedVersionServiceServer) Version(ctx context.Context, req *VersionRequest) (*APIVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}

func RegisterVersionServiceServer(s *grpc.Server, srv VersionServiceServer) {
	s.RegisterService(&_VersionService_serviceDesc, srv)
}

func _VersionService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.VersionService/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VersionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.VersionService",
	HandlerType: (*VersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _VersionService_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version.proto",
}
