/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Metadata             *ObjectMeta    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *AccountSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *AccountStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Account) GetSpec() *AccountSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Account) GetStatus() *AccountStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type AccountSpec struct {
	Metadata             *AccountMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Roles                []string         `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Subjects             []*Subject       `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountSpec) Reset()         { *m = AccountSpec{} }
func (m *AccountSpec) String() string { return proto.CompactTextString(m) }
func (*AccountSpec) ProtoMessage()    {}
func (*AccountSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *AccountSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSpec.Unmarshal(m, b)
}
func (m *AccountSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSpec.Marshal(b, m, deterministic)
}
func (m *AccountSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSpec.Merge(m, src)
}
func (m *AccountSpec) XXX_Size() int {
	return xxx_messageInfo_AccountSpec.Size(m)
}
func (m *AccountSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSpec.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSpec proto.InternalMessageInfo

func (m *AccountSpec) GetMetadata() *AccountMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AccountSpec) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AccountSpec) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type AccountMetadata struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription     string   `protobuf:"bytes,3,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Logo                 *Image   `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Icon                 *Image   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountMetadata) Reset()         { *m = AccountMetadata{} }
func (m *AccountMetadata) String() string { return proto.CompactTextString(m) }
func (*AccountMetadata) ProtoMessage()    {}
func (*AccountMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *AccountMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMetadata.Unmarshal(m, b)
}
func (m *AccountMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMetadata.Marshal(b, m, deterministic)
}
func (m *AccountMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMetadata.Merge(m, src)
}
func (m *AccountMetadata) XXX_Size() int {
	return xxx_messageInfo_AccountMetadata.Size(m)
}
func (m *AccountMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMetadata proto.InternalMessageInfo

func (m *AccountMetadata) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *AccountMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AccountMetadata) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *AccountMetadata) GetLogo() *Image {
	if m != nil {
		return m.Logo
	}
	return nil
}

func (m *AccountMetadata) GetIcon() *Image {
	if m != nil {
		return m.Icon
	}
	return nil
}

type Subject struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiGroup             string   `protobuf:"bytes,2,opt,name=apiGroup,proto3" json:"apiGroup,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Subject) GetApiGroup() string {
	if m != nil {
		return m.ApiGroup
	}
	return ""
}

func (m *Subject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Subject) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type AccountStatus struct {
	Namespace            *ObjectReference    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ObservedGeneration   int64               `protobuf:"varint,2,opt,name=observedGeneration,proto3" json:"observedGeneration,omitempty"`
	Phase                string              `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Conditions           []*AccountCondition `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AccountStatus) Reset()         { *m = AccountStatus{} }
func (m *AccountStatus) String() string { return proto.CompactTextString(m) }
func (*AccountStatus) ProtoMessage()    {}
func (*AccountStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *AccountStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountStatus.Unmarshal(m, b)
}
func (m *AccountStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountStatus.Marshal(b, m, deterministic)
}
func (m *AccountStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStatus.Merge(m, src)
}
func (m *AccountStatus) XXX_Size() int {
	return xxx_messageInfo_AccountStatus.Size(m)
}
func (m *AccountStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStatus proto.InternalMessageInfo

func (m *AccountStatus) GetNamespace() *ObjectReference {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *AccountStatus) GetObservedGeneration() int64 {
	if m != nil {
		return m.ObservedGeneration
	}
	return 0
}

func (m *AccountStatus) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *AccountStatus) GetConditions() []*AccountCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type AccountCondition struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastTransitionTime   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
	Reason               string               `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountCondition) Reset()         { *m = AccountCondition{} }
func (m *AccountCondition) String() string { return proto.CompactTextString(m) }
func (*AccountCondition) ProtoMessage()    {}
func (*AccountCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *AccountCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCondition.Unmarshal(m, b)
}
func (m *AccountCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCondition.Marshal(b, m, deterministic)
}
func (m *AccountCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCondition.Merge(m, src)
}
func (m *AccountCondition) XXX_Size() int {
	return xxx_messageInfo_AccountCondition.Size(m)
}
func (m *AccountCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCondition.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCondition proto.InternalMessageInfo

func (m *AccountCondition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AccountCondition) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AccountCondition) GetLastTransitionTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastTransitionTime
	}
	return nil
}

func (m *AccountCondition) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *AccountCondition) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AccountList struct {
	Metadata             *ListMeta  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Account `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountList) Reset()         { *m = AccountList{} }
func (m *AccountList) String() string { return proto.CompactTextString(m) }
func (*AccountList) ProtoMessage()    {}
func (*AccountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *AccountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountList.Unmarshal(m, b)
}
func (m *AccountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountList.Marshal(b, m, deterministic)
}
func (m *AccountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountList.Merge(m, src)
}
func (m *AccountList) XXX_Size() int {
	return xxx_messageInfo_AccountList.Size(m)
}
func (m *AccountList) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountList.DiscardUnknown(m)
}

var xxx_messageInfo_AccountList proto.InternalMessageInfo

func (m *AccountList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AccountList) GetItems() []*Account {
	if m != nil {
		return m.Items
	}
	return nil
}

type AccountGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountGetRequest) Reset()         { *m = AccountGetRequest{} }
func (m *AccountGetRequest) String() string { return proto.CompactTextString(m) }
func (*AccountGetRequest) ProtoMessage()    {}
func (*AccountGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *AccountGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountGetRequest.Unmarshal(m, b)
}
func (m *AccountGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountGetRequest.Marshal(b, m, deterministic)
}
func (m *AccountGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountGetRequest.Merge(m, src)
}
func (m *AccountGetRequest) XXX_Size() int {
	return xxx_messageInfo_AccountGetRequest.Size(m)
}
func (m *AccountGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountGetRequest proto.InternalMessageInfo

func (m *AccountGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AccountListRequest struct {
	LabelSelector        string   `protobuf:"bytes,1,opt,name=labelSelector,proto3" json:"labelSelector,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Continue             string   `protobuf:"bytes,3,opt,name=continue,proto3" json:"continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountListRequest) Reset()         { *m = AccountListRequest{} }
func (m *AccountListRequest) String() string { return proto.CompactTextString(m) }
func (*AccountListRequest) ProtoMessage()    {}
func (*AccountListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *AccountListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountListRequest.Unmarshal(m, b)
}
func (m *AccountListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountListRequest.Marshal(b, m, deterministic)
}
func (m *AccountListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountListRequest.Merge(m, src)
}
func (m *AccountListRequest) XXX_Size() int {
	return xxx_messageInfo_AccountListRequest.Size(m)
}
func (m *AccountListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountListRequest proto.InternalMessageInfo

func (m *AccountListRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *AccountListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AccountListRequest) GetContinue() string {
	if m != nil {
		return m.Continue
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "kubecarrier.api.v1.Account")
	proto.RegisterType((*AccountSpec)(nil), "kubecarrier.api.v1.AccountSpec")
	proto.RegisterType((*AccountMetadata)(nil), "kubecarrier.api.v1.AccountMetadata")
	proto.RegisterType((*Subject)(nil), "kubecarrier.api.v1.Subject")
	proto.RegisterType((*AccountStatus)(nil), "kubecarrier.api.v1.AccountStatus")
	proto.RegisterType((*AccountCondition)(nil), "kubecarrier.api.v1.AccountCondition")
	proto.RegisterType((*AccountList)(nil), "kubecarrier.api.v1.AccountList")
	proto.RegisterType((*AccountGetRequest)(nil), "kubecarrier.api.v1.AccountGetRequest")
	proto.RegisterType((*AccountListRequest)(nil), "kubecarrier.api.v1.AccountListRequest")
}

func init() {
	proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0)
}

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x96, 0x93, 0xf4, 0x27, 0x27, 0xb7, 0xbd, 0xbd, 0x73, 0x7b, 0xaf, 0x4c, 0x5a, 0xd1, 0x62,
	0x0a, 0x54, 0x48, 0x38, 0x4a, 0xba, 0xe0, 0x67, 0x83, 0x0a, 0x95, 0x22, 0x10, 0x05, 0xc9, 0xed,
	0x8a, 0xdd, 0xc4, 0x39, 0x4d, 0x87, 0xda, 0x1e, 0x33, 0x33, 0x8e, 0x54, 0x10, 0x1b, 0x5e, 0x81,
	0x35, 0x8f, 0xc1, 0x8e, 0xb7, 0x60, 0x4f, 0x37, 0x3c, 0x08, 0x9a, 0xf1, 0xd8, 0x71, 0x9b, 0x90,
	0xae, 0x32, 0x67, 0xfc, 0x7d, 0x73, 0xce, 0xf9, 0xe6, 0x3b, 0x13, 0x58, 0xa1, 0x61, 0xc8, 0xb3,
	0x44, 0xf9, 0xa9, 0xe0, 0x8a, 0x13, 0x72, 0x96, 0x0d, 0x30, 0xa4, 0x42, 0x30, 0x14, 0x3e, 0x4d,
	0x99, 0x3f, 0xee, 0xb6, 0x37, 0x47, 0x9c, 0x8f, 0x22, 0xec, 0xd0, 0x94, 0x75, 0x68, 0x92, 0x70,
	0x45, 0x15, 0xe3, 0x89, 0xcc, 0x19, 0xed, 0x2d, 0xfb, 0xd5, 0x44, 0x83, 0xec, 0xa4, 0xa3, 0x58,
	0x8c, 0x52, 0xd1, 0x38, 0xb5, 0x00, 0x88, 0x51, 0x51, 0xbb, 0x6e, 0xa9, 0xf3, 0x14, 0x2d, 0xd3,
	0xfb, 0xe6, 0xc0, 0xd2, 0x7e, 0x9e, 0x9d, 0x3c, 0x81, 0x65, 0x0d, 0x1b, 0x52, 0x45, 0x5d, 0x67,
	0xdb, 0xd9, 0x6d, 0xf5, 0x6e, 0xfa, 0xd3, 0xa5, 0xf8, 0x6f, 0x06, 0xef, 0x30, 0x54, 0x87, 0xa8,
	0x68, 0x50, 0xe2, 0xc9, 0x1e, 0x34, 0x64, 0x8a, 0xa1, 0x5b, 0x33, 0xbc, 0xad, 0x59, 0x3c, 0x9b,
	0xe6, 0x28, 0xc5, 0x30, 0x30, 0x60, 0xf2, 0x18, 0x16, 0xa5, 0xa2, 0x2a, 0x93, 0x6e, 0xdd, 0xd0,
	0x6e, 0xcd, 0xa3, 0x19, 0x60, 0x60, 0x09, 0xde, 0x57, 0x07, 0x5a, 0x95, 0x03, 0xc9, 0xd3, 0xa9,
	0xda, 0x6f, 0xcf, 0x39, 0xec, 0xd0, 0x42, 0x2b, 0x0d, 0xac, 0xc3, 0x82, 0xe0, 0x11, 0x4a, 0xb7,
	0xb6, 0x5d, 0xdf, 0x6d, 0x06, 0x79, 0x40, 0x1e, 0xc2, 0xb2, 0xcc, 0x4c, 0xbf, 0xba, 0xc6, 0xfa,
	0x6e, 0xab, 0xb7, 0x31, 0xeb, 0xd8, 0xa3, 0x1c, 0x13, 0x94, 0x60, 0xef, 0xc2, 0x81, 0xbf, 0xaf,
	0x24, 0x23, 0xdb, 0xd0, 0x1a, 0x32, 0x99, 0x46, 0xf4, 0xfc, 0x35, 0x8d, 0xd1, 0x94, 0xd9, 0x0c,
	0xaa, 0x5b, 0x06, 0x81, 0x32, 0x14, 0x2c, 0xd5, 0xb7, 0x6b, 0xc4, 0xd4, 0x88, 0xc9, 0x16, 0xb9,
	0x0f, 0x6b, 0xf2, 0x94, 0x0b, 0x75, 0x50, 0x81, 0xd5, 0x0d, 0x6c, 0x6a, 0x9f, 0x3c, 0x80, 0x46,
	0xc4, 0x47, 0xdc, 0x6d, 0x18, 0x3d, 0x6e, 0xcc, 0x2a, 0xfc, 0x45, 0x4c, 0x47, 0x18, 0x18, 0x98,
	0x86, 0xb3, 0x90, 0x27, 0xee, 0xc2, 0xb5, 0x70, 0x0d, 0xf3, 0xce, 0x60, 0xc9, 0xb6, 0x4d, 0x08,
	0x34, 0xce, 0x58, 0x32, 0xb4, 0x1d, 0x99, 0x35, 0x69, 0xc3, 0x32, 0x4d, 0x59, 0x5f, 0xf0, 0x2c,
	0xb5, 0x7d, 0x94, 0xb1, 0xc6, 0x27, 0x5a, 0x81, 0xbc, 0x70, 0xb3, 0x26, 0x9b, 0xd0, 0xd4, 0xbf,
	0x32, 0xa5, 0x21, 0x9a, 0x8a, 0x9b, 0xc1, 0x64, 0xc3, 0xfb, 0xe9, 0xc0, 0xca, 0x25, 0x23, 0x90,
	0xfd, 0x2a, 0x7e, 0xce, 0x8d, 0xe7, 0x6e, 0x0d, 0xf0, 0x04, 0x05, 0x26, 0x21, 0x56, 0x0e, 0x25,
	0x3e, 0x10, 0x3e, 0x90, 0x28, 0xc6, 0x38, 0xec, 0x63, 0x82, 0x82, 0x96, 0xa2, 0xd7, 0x83, 0x19,
	0x5f, 0xb4, 0x45, 0xd2, 0x53, 0x2a, 0x8b, 0xba, 0xf3, 0x80, 0x1c, 0x00, 0x84, 0x3c, 0x19, 0x32,
	0x33, 0x8f, 0x6e, 0xc3, 0x98, 0x64, 0x67, 0x8e, 0xf7, 0x9e, 0x17, 0xe0, 0xa0, 0xc2, 0xf3, 0xbe,
	0x3b, 0xb0, 0x76, 0x15, 0xa0, 0x75, 0xd2, 0xb3, 0x5a, 0xe8, 0xaa, 0xd7, 0xe4, 0xff, 0x72, 0x66,
	0x72, 0x55, 0x6d, 0x44, 0x5e, 0x02, 0x89, 0xa8, 0x54, 0xc7, 0x82, 0x26, 0xd2, 0xb0, 0x8f, 0x99,
	0x55, 0xb8, 0xd5, 0x6b, 0xfb, 0xf9, 0xfb, 0xe0, 0x17, 0xef, 0x83, 0x7f, 0x5c, 0xbc, 0x0f, 0xc1,
	0x0c, 0x96, 0xce, 0x21, 0x90, 0x4a, 0x9e, 0xd8, 0x8b, 0xb0, 0x11, 0x71, 0x61, 0x29, 0x46, 0x29,
	0xe9, 0x08, 0x8d, 0x49, 0x9a, 0x41, 0x11, 0x7a, 0x1f, 0xca, 0x69, 0x7c, 0xc5, 0xa4, 0x22, 0x8f,
	0xa6, 0xa6, 0x71, 0x73, 0x96, 0x22, 0x1a, 0x7b, 0xe5, 0x1d, 0xe9, 0xc2, 0x02, 0x53, 0x18, 0xe7,
	0x63, 0xf8, 0x87, 0x69, 0xb3, 0x99, 0x82, 0x1c, 0xe9, 0xdd, 0x83, 0x7f, 0xec, 0x4e, 0x1f, 0x55,
	0x80, 0xef, 0x33, 0x94, 0xaa, 0xb4, 0x98, 0x33, 0xb1, 0x98, 0x17, 0x01, 0xa9, 0x14, 0x59, 0x20,
	0x77, 0x60, 0x25, 0xa2, 0x03, 0x8c, 0x8e, 0x30, 0xc2, 0x50, 0x71, 0x61, 0x29, 0x97, 0x37, 0xf5,
	0xdd, 0x47, 0x2c, 0x66, 0xca, 0xda, 0x23, 0x0f, 0xb4, 0xc9, 0x43, 0x9e, 0x28, 0x96, 0x64, 0x85,
	0x29, 0xca, 0xb8, 0x77, 0xe1, 0xc0, 0x6a, 0x61, 0x59, 0x14, 0x63, 0x16, 0x22, 0x41, 0x68, 0x18,
	0x79, 0xee, 0xce, 0xe9, 0xaa, 0x52, 0x5a, 0x7b, 0xeb, 0x1a, 0x9c, 0xb7, 0xfe, 0xf9, 0xc7, 0xaf,
	0x2f, 0xb5, 0x55, 0xf2, 0x57, 0x67, 0xdc, 0xed, 0xd8, 0x3f, 0x11, 0x49, 0x4e, 0xa0, 0xde, 0x47,
	0x45, 0xee, 0xcc, 0x61, 0x4f, 0x94, 0x6a, 0xcf, 0x93, 0xd8, 0xdb, 0x30, 0x09, 0xfe, 0x23, 0xff,
	0x56, 0x13, 0x74, 0x3e, 0x6a, 0x39, 0x3f, 0x3d, 0x6b, 0xbc, 0xad, 0x8d, 0xbb, 0x83, 0x45, 0x63,
	0xaa, 0xbd, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x8f, 0xaa, 0x8d, 0xc5, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	List(ctx context.Context, in *AccountListRequest, opts ...grpc.CallOption) (*AccountList, error)
	Get(ctx context.Context, in *AccountGetRequest, opts ...grpc.CallOption) (*Account, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) List(ctx context.Context, in *AccountListRequest, opts ...grpc.CallOption) (*AccountList, error) {
	out := new(AccountList)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.AccountService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Get(ctx context.Context, in *AccountGetRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.AccountService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	List(context.Context, *AccountListRequest) (*AccountList, error)
	Get(context.Context, *AccountGetRequest) (*Account, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) List(ctx context.Context, req *AccountListRequest) (*AccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAccountServiceServer) Get(ctx context.Context, req *AccountGetRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.AccountService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).List(ctx, req.(*AccountListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.AccountService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Get(ctx, req.(*AccountGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
