/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WatchEvent struct {
	Object               *any.Any `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchEvent) Reset()         { *m = WatchEvent{} }
func (m *WatchEvent) String() string { return proto.CompactTextString(m) }
func (*WatchEvent) ProtoMessage()    {}
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *WatchEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchEvent.Unmarshal(m, b)
}
func (m *WatchEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchEvent.Marshal(b, m, deterministic)
}
func (m *WatchEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchEvent.Merge(m, src)
}
func (m *WatchEvent) XXX_Size() int {
	return xxx_messageInfo_WatchEvent.Size(m)
}
func (m *WatchEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchEvent.DiscardUnknown(m)
}

var xxx_messageInfo_WatchEvent proto.InternalMessageInfo

func (m *WatchEvent) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *WatchEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*WatchEvent)(nil), "kubecarrier.api.v1.WatchEvent")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xca, 0x2e, 0x4d, 0x4a, 0x4d, 0x4e, 0x2c,
	0x2a, 0xca, 0x4c, 0x2d, 0xd2, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0x94, 0x92, 0x4c, 0xcf, 0xcf,
	0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xab, 0x48, 0x2a, 0x4d, 0xd3, 0x4f, 0xcc, 0xab, 0x84, 0x28, 0x57,
	0xf2, 0xe3, 0xe2, 0x0a, 0x4f, 0x2c, 0x49, 0xce, 0x70, 0x05, 0x19, 0x21, 0xa4, 0xc3, 0xc5, 0x96,
	0x9f, 0x94, 0x95, 0x9a, 0x5c, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0xd1,
	0xa9, 0x07, 0xd3, 0xa9, 0xe7, 0x98, 0x57, 0x19, 0x04, 0x55, 0x23, 0x24, 0xc4, 0xc5, 0x52, 0x52,
	0x59, 0x90, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x3b, 0xb1, 0x44, 0x31, 0x95,
	0x19, 0x26, 0xb1, 0x81, 0xd5, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xce, 0x1b, 0x0c, 0xcd,
	0x9a, 0x00, 0x00, 0x00,
}
