/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: instance.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instance struct {
	// Metadata - common metadata
	Metadata *ObjectMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Offering name, i.e. couchdb.eu-west-1.team-a
	Offering string `protobuf:"bytes,2,opt,name=offering,proto3" json:"offering,omitempty"`
	// Spec - instance spec
	Spec *RawObject `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Status - instance status
	Status               *RawObject `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Instance) GetOffering() string {
	if m != nil {
		return m.Offering
	}
	return ""
}

func (m *Instance) GetSpec() *RawObject {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Instance) GetStatus() *RawObject {
	if m != nil {
		return m.Status
	}
	return nil
}

type InstanceList struct {
	Metadata             *ListMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Instance `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InstanceList) Reset()         { *m = InstanceList{} }
func (m *InstanceList) String() string { return proto.CompactTextString(m) }
func (*InstanceList) ProtoMessage()    {}
func (*InstanceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{1}
}

func (m *InstanceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceList.Unmarshal(m, b)
}
func (m *InstanceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceList.Marshal(b, m, deterministic)
}
func (m *InstanceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceList.Merge(m, src)
}
func (m *InstanceList) XXX_Size() int {
	return xxx_messageInfo_InstanceList.Size(m)
}
func (m *InstanceList) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceList.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceList proto.InternalMessageInfo

func (m *InstanceList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *InstanceList) GetItems() []*Instance {
	if m != nil {
		return m.Items
	}
	return nil
}

type InstanceGetRequest struct {
	// Offering name, i.e. couchdb.eu-west-1.team-a
	Offering string `protobuf:"bytes,1,opt,name=offering,proto3" json:"offering,omitempty"`
	// Version of the resource
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Name of the offering instance
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Account indicate namespace of the project/account
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGetRequest) Reset()         { *m = InstanceGetRequest{} }
func (m *InstanceGetRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceGetRequest) ProtoMessage()    {}
func (*InstanceGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{2}
}

func (m *InstanceGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGetRequest.Unmarshal(m, b)
}
func (m *InstanceGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGetRequest.Marshal(b, m, deterministic)
}
func (m *InstanceGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGetRequest.Merge(m, src)
}
func (m *InstanceGetRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceGetRequest.Size(m)
}
func (m *InstanceGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGetRequest proto.InternalMessageInfo

func (m *InstanceGetRequest) GetOffering() string {
	if m != nil {
		return m.Offering
	}
	return ""
}

func (m *InstanceGetRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InstanceGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstanceGetRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type InstanceDeleteRequest struct {
	// Offering name, i.e. couchdb.eu-west-1.team-a
	Offering string `protobuf:"bytes,1,opt,name=offering,proto3" json:"offering,omitempty"`
	// Version of the resource
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Name of the offering instance
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Account indicate namespace of the project/account
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceDeleteRequest) Reset()         { *m = InstanceDeleteRequest{} }
func (m *InstanceDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceDeleteRequest) ProtoMessage()    {}
func (*InstanceDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{3}
}

func (m *InstanceDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceDeleteRequest.Unmarshal(m, b)
}
func (m *InstanceDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceDeleteRequest.Marshal(b, m, deterministic)
}
func (m *InstanceDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceDeleteRequest.Merge(m, src)
}
func (m *InstanceDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceDeleteRequest.Size(m)
}
func (m *InstanceDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceDeleteRequest proto.InternalMessageInfo

func (m *InstanceDeleteRequest) GetOffering() string {
	if m != nil {
		return m.Offering
	}
	return ""
}

func (m *InstanceDeleteRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InstanceDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstanceDeleteRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type InstanceListRequest struct {
	// Offering name, i.e. couchdb.eu-west-1.team-a
	Offering string `protobuf:"bytes,1,opt,name=offering,proto3" json:"offering,omitempty"`
	// Version of the resource
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Account indicate namespace of the project/account
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	LabelSelector        string   `protobuf:"bytes,4,opt,name=labelSelector,proto3" json:"labelSelector,omitempty"`
	Limit                int64    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Continue             string   `protobuf:"bytes,6,opt,name=continue,proto3" json:"continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceListRequest) Reset()         { *m = InstanceListRequest{} }
func (m *InstanceListRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceListRequest) ProtoMessage()    {}
func (*InstanceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{4}
}

func (m *InstanceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceListRequest.Unmarshal(m, b)
}
func (m *InstanceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceListRequest.Marshal(b, m, deterministic)
}
func (m *InstanceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceListRequest.Merge(m, src)
}
func (m *InstanceListRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceListRequest.Size(m)
}
func (m *InstanceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceListRequest proto.InternalMessageInfo

func (m *InstanceListRequest) GetOffering() string {
	if m != nil {
		return m.Offering
	}
	return ""
}

func (m *InstanceListRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InstanceListRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *InstanceListRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *InstanceListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *InstanceListRequest) GetContinue() string {
	if m != nil {
		return m.Continue
	}
	return ""
}

type InstanceCreateRequest struct {
	// Offering name, i.e. couchdb.eu-west-1.team-a
	Offering string `protobuf:"bytes,1,opt,name=offering,proto3" json:"offering,omitempty"`
	// Version of the resource
	Version string    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Spec    *Instance `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Account indicate namespace of the project/account
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceCreateRequest) Reset()         { *m = InstanceCreateRequest{} }
func (m *InstanceCreateRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceCreateRequest) ProtoMessage()    {}
func (*InstanceCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{5}
}

func (m *InstanceCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceCreateRequest.Unmarshal(m, b)
}
func (m *InstanceCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceCreateRequest.Marshal(b, m, deterministic)
}
func (m *InstanceCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceCreateRequest.Merge(m, src)
}
func (m *InstanceCreateRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceCreateRequest.Size(m)
}
func (m *InstanceCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceCreateRequest proto.InternalMessageInfo

func (m *InstanceCreateRequest) GetOffering() string {
	if m != nil {
		return m.Offering
	}
	return ""
}

func (m *InstanceCreateRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InstanceCreateRequest) GetSpec() *Instance {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *InstanceCreateRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type RawObject struct {
	// Encoding of the object data
	Encoding string `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`
	// Data - actual data
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawObject) Reset()         { *m = RawObject{} }
func (m *RawObject) String() string { return proto.CompactTextString(m) }
func (*RawObject) ProtoMessage()    {}
func (*RawObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{6}
}

func (m *RawObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawObject.Unmarshal(m, b)
}
func (m *RawObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawObject.Marshal(b, m, deterministic)
}
func (m *RawObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawObject.Merge(m, src)
}
func (m *RawObject) XXX_Size() int {
	return xxx_messageInfo_RawObject.Size(m)
}
func (m *RawObject) XXX_DiscardUnknown() {
	xxx_messageInfo_RawObject.DiscardUnknown(m)
}

var xxx_messageInfo_RawObject proto.InternalMessageInfo

func (m *RawObject) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *RawObject) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Instance)(nil), "kubecarrier.api.v1.Instance")
	proto.RegisterType((*InstanceList)(nil), "kubecarrier.api.v1.InstanceList")
	proto.RegisterType((*InstanceGetRequest)(nil), "kubecarrier.api.v1.InstanceGetRequest")
	proto.RegisterType((*InstanceDeleteRequest)(nil), "kubecarrier.api.v1.InstanceDeleteRequest")
	proto.RegisterType((*InstanceListRequest)(nil), "kubecarrier.api.v1.InstanceListRequest")
	proto.RegisterType((*InstanceCreateRequest)(nil), "kubecarrier.api.v1.InstanceCreateRequest")
	proto.RegisterType((*RawObject)(nil), "kubecarrier.api.v1.RawObject")
}

func init() {
	proto.RegisterFile("instance.proto", fileDescriptor_fd22322185b2070b)
}

var fileDescriptor_fd22322185b2070b = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0x6d, 0xb6, 0xb6, 0xe3, 0x2a, 0x32, 0xfe, 0x10, 0xe2, 0x2a, 0x25, 0x88, 0x56, 0x2f,
	0x12, 0x5b, 0x59, 0x94, 0xd5, 0xf5, 0xc2, 0x5d, 0x59, 0x04, 0x45, 0xc8, 0xde, 0x79, 0x37, 0xcd,
	0x9e, 0x96, 0xd1, 0x74, 0xa6, 0x66, 0x4e, 0xaa, 0x52, 0x7b, 0xe3, 0x13, 0x28, 0x82, 0xe0, 0xc3,
	0xf8, 0x06, 0xde, 0xf9, 0x0a, 0xe2, 0x73, 0x48, 0x26, 0x99, 0x6e, 0xb3, 0x3f, 0x59, 0xd9, 0x82,
	0x77, 0x73, 0x66, 0xce, 0xcc, 0xf7, 0x9d, 0x6f, 0xbe, 0x73, 0xc8, 0x79, 0x2e, 0x14, 0x32, 0x11,
	0x81, 0x3f, 0x4e, 0x24, 0x4a, 0x4a, 0xdf, 0xa4, 0x7d, 0x88, 0x58, 0x92, 0x70, 0x48, 0x7c, 0x36,
	0xe6, 0xfe, 0xa4, 0xeb, 0xae, 0x0d, 0xa5, 0x1c, 0xc6, 0x10, 0xb0, 0x31, 0x0f, 0x98, 0x10, 0x12,
	0x19, 0x72, 0x29, 0x54, 0x7e, 0xc3, 0xbd, 0x5a, 0x9c, 0xea, 0xa8, 0x9f, 0x0e, 0x02, 0x18, 0x8d,
	0xf1, 0x43, 0x71, 0x48, 0x46, 0x80, 0x2c, 0x5f, 0x7b, 0x3f, 0x2d, 0xd2, 0x7c, 0x56, 0xa0, 0xd1,
	0x0d, 0xd2, 0xcc, 0x8e, 0xf6, 0x18, 0x32, 0xc7, 0x6a, 0x5b, 0x9d, 0xb3, 0xbd, 0xeb, 0xfe, 0x61,
	0x68, 0xff, 0x65, 0xff, 0x35, 0x44, 0xf8, 0x02, 0x90, 0x85, 0xf3, 0x7c, 0xea, 0x92, 0xa6, 0x1c,
	0x0c, 0x20, 0xe1, 0x62, 0xe8, 0xd4, 0xda, 0x56, 0xa7, 0x15, 0xce, 0x63, 0xda, 0x25, 0xb6, 0x1a,
	0x43, 0xe4, 0xd4, 0xf5, 0x9b, 0xd7, 0x8e, 0x7a, 0x33, 0x64, 0xef, 0xf2, 0x67, 0x43, 0x9d, 0x4a,
	0xd7, 0x49, 0x43, 0x21, 0xc3, 0x54, 0x39, 0xf6, 0xbf, 0x5c, 0x2a, 0x92, 0xbd, 0x8f, 0x64, 0xd5,
	0x54, 0xf3, 0x9c, 0x2b, 0xa4, 0x0f, 0x0e, 0x55, 0xb4, 0x76, 0xd4, 0x43, 0x59, 0xee, 0x81, 0x7a,
	0x7a, 0x64, 0x85, 0x23, 0x8c, 0x94, 0x53, 0x6b, 0xd7, 0x8f, 0xbb, 0x66, 0xa0, 0xc2, 0x3c, 0xd5,
	0x7b, 0x4f, 0xa8, 0xd9, 0xda, 0x01, 0x0c, 0xe1, 0x6d, 0x0a, 0x0a, 0x4b, 0xca, 0x58, 0x07, 0x94,
	0x71, 0xc8, 0x99, 0x09, 0x24, 0x8a, 0x4b, 0x51, 0x88, 0x66, 0x42, 0x4a, 0x89, 0x2d, 0xd8, 0x08,
	0xb4, 0x66, 0xad, 0x50, 0xaf, 0xb3, 0x6c, 0x16, 0x45, 0x32, 0x15, 0xa8, 0x55, 0x69, 0x85, 0x26,
	0xf4, 0xa6, 0xe4, 0xb2, 0x41, 0xde, 0x86, 0x18, 0x10, 0xfe, 0x27, 0xf8, 0x0f, 0x8b, 0x5c, 0x5c,
	0x54, 0x7d, 0x39, 0xec, 0x05, 0x9c, 0x7a, 0x09, 0x87, 0xde, 0x20, 0xe7, 0x62, 0xd6, 0x87, 0x78,
	0x17, 0x62, 0x88, 0x50, 0x26, 0x05, 0x8f, 0xf2, 0x26, 0xbd, 0x44, 0x56, 0x62, 0x3e, 0xe2, 0xe8,
	0xac, 0xb4, 0xad, 0x4e, 0x3d, 0xcc, 0x83, 0x8c, 0x4b, 0x24, 0x05, 0x72, 0x91, 0x82, 0xd3, 0xc8,
	0xb9, 0x98, 0xd8, 0xfb, 0x6e, 0xed, 0xab, 0xb7, 0x95, 0x00, 0x5b, 0x56, 0xbd, 0xbb, 0x25, 0xbb,
	0x57, 0x3b, 0x27, 0x77, 0xfb, 0xf1, 0xda, 0x3e, 0x24, 0xad, 0xb9, 0xcb, 0x33, 0x3a, 0x20, 0x22,
	0xb9, 0xb7, 0x40, 0xc7, 0xc4, 0xd9, 0x97, 0x69, 0x97, 0x67, 0x5c, 0x56, 0x43, 0xbd, 0xee, 0xfd,
	0xb1, 0xc9, 0x05, 0x83, 0xa4, 0x76, 0x21, 0x99, 0xf0, 0x08, 0xe8, 0x67, 0x8b, 0xd8, 0xba, 0x37,
	0x6e, 0x55, 0x11, 0x5b, 0xf8, 0x47, 0xb7, 0x7d, 0x52, 0xa2, 0xb7, 0xf9, 0xe9, 0xd7, 0xef, 0xaf,
	0xb5, 0xfb, 0x74, 0x3d, 0x98, 0x74, 0x83, 0x82, 0xba, 0x0a, 0xa6, 0xc5, 0x6a, 0x16, 0x98, 0x79,
	0xa6, 0x82, 0xa9, 0xd1, 0x6f, 0x16, 0x4c, 0x0b, 0xbd, 0x66, 0xf4, 0x8b, 0x45, 0xea, 0x3b, 0x80,
	0xf4, 0x66, 0x15, 0xd0, 0x7e, 0x47, 0xb9, 0x95, 0x92, 0x7a, 0xdb, 0x9a, 0xcc, 0x63, 0xfa, 0xe8,
	0x54, 0x64, 0x82, 0x69, 0xe6, 0x76, 0xcd, 0xa9, 0x91, 0xb7, 0x12, 0xbd, 0x5d, 0x05, 0x57, 0x6a,
	0x37, 0xf7, 0x8a, 0x9f, 0x0f, 0x5e, 0xdf, 0x0c, 0x5e, 0xff, 0x69, 0x36, 0x78, 0x0d, 0xa7, 0x3b,
	0xcb, 0x71, 0xfa, 0x66, 0x91, 0x46, 0x6e, 0xd0, 0x6a, 0x4e, 0x25, 0x13, 0x9f, 0xa0, 0xd6, 0x96,
	0x66, 0xb6, 0xe9, 0x9d, 0xee, 0xeb, 0x36, 0xb4, 0x7f, 0x9f, 0xd8, 0xaf, 0x6a, 0x93, 0x6e, 0xbf,
	0xa1, 0x8b, 0xbe, 0xf7, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xfc, 0x7c, 0x88, 0xbf, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InstancesServiceClient is the client API for InstancesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstancesServiceClient interface {
	List(ctx context.Context, in *InstanceListRequest, opts ...grpc.CallOption) (*InstanceList, error)
	Get(ctx context.Context, in *InstanceGetRequest, opts ...grpc.CallOption) (*Instance, error)
	Delete(ctx context.Context, in *InstanceDeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Create(ctx context.Context, in *InstanceCreateRequest, opts ...grpc.CallOption) (*Instance, error)
}

type instancesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstancesServiceClient(cc grpc.ClientConnInterface) InstancesServiceClient {
	return &instancesServiceClient{cc}
}

func (c *instancesServiceClient) List(ctx context.Context, in *InstanceListRequest, opts ...grpc.CallOption) (*InstanceList, error) {
	out := new(InstanceList)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.InstancesService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instancesServiceClient) Get(ctx context.Context, in *InstanceGetRequest, opts ...grpc.CallOption) (*Instance, error) {
	out := new(Instance)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.InstancesService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instancesServiceClient) Delete(ctx context.Context, in *InstanceDeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.InstancesService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instancesServiceClient) Create(ctx context.Context, in *InstanceCreateRequest, opts ...grpc.CallOption) (*Instance, error) {
	out := new(Instance)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.InstancesService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstancesServiceServer is the server API for InstancesService service.
type InstancesServiceServer interface {
	List(context.Context, *InstanceListRequest) (*InstanceList, error)
	Get(context.Context, *InstanceGetRequest) (*Instance, error)
	Delete(context.Context, *InstanceDeleteRequest) (*empty.Empty, error)
	Create(context.Context, *InstanceCreateRequest) (*Instance, error)
}

// UnimplementedInstancesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInstancesServiceServer struct {
}

func (*UnimplementedInstancesServiceServer) List(ctx context.Context, req *InstanceListRequest) (*InstanceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedInstancesServiceServer) Get(ctx context.Context, req *InstanceGetRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedInstancesServiceServer) Delete(ctx context.Context, req *InstanceDeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedInstancesServiceServer) Create(ctx context.Context, req *InstanceCreateRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterInstancesServiceServer(s *grpc.Server, srv InstancesServiceServer) {
	s.RegisterService(&_InstancesService_serviceDesc, srv)
}

func _InstancesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstancesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.InstancesService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstancesServiceServer).List(ctx, req.(*InstanceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstancesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstancesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.InstancesService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstancesServiceServer).Get(ctx, req.(*InstanceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstancesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstancesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.InstancesService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstancesServiceServer).Delete(ctx, req.(*InstanceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstancesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstancesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.InstancesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstancesServiceServer).Create(ctx, req.(*InstanceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InstancesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.InstancesService",
	HandlerType: (*InstancesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _InstancesService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _InstancesService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _InstancesService_Delete_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _InstancesService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "instance.proto",
}
