/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObjectMeta struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreationTimestamp    *timestamp.Timestamp `protobuf:"bytes,3,opt,name=creationTimestamp,proto3" json:"creationTimestamp,omitempty"`
	DeletionTimestamp    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deletionTimestamp,proto3" json:"deletionTimestamp,omitempty"`
	ResourceVersion      string               `protobuf:"bytes,5,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	Labels               map[string]string    `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations          map[string]string    `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Generation           int64                `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ObjectMeta) Reset()         { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()    {}
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *ObjectMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectMeta.Unmarshal(m, b)
}
func (m *ObjectMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectMeta.Marshal(b, m, deterministic)
}
func (m *ObjectMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectMeta.Merge(m, src)
}
func (m *ObjectMeta) XXX_Size() int {
	return xxx_messageInfo_ObjectMeta.Size(m)
}
func (m *ObjectMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectMeta proto.InternalMessageInfo

func (m *ObjectMeta) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ObjectMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectMeta) GetCreationTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTimestamp
	}
	return nil
}

func (m *ObjectMeta) GetDeletionTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.DeletionTimestamp
	}
	return nil
}

func (m *ObjectMeta) GetResourceVersion() string {
	if m != nil {
		return m.ResourceVersion
	}
	return ""
}

func (m *ObjectMeta) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ObjectMeta) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *ObjectMeta) GetGeneration() int64 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type ListMeta struct {
	Continue             string   `protobuf:"bytes,1,opt,name=continue,proto3" json:"continue,omitempty"`
	ResourceVersion      string   `protobuf:"bytes,2,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMeta) Reset()         { *m = ListMeta{} }
func (m *ListMeta) String() string { return proto.CompactTextString(m) }
func (*ListMeta) ProtoMessage()    {}
func (*ListMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

func (m *ListMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeta.Unmarshal(m, b)
}
func (m *ListMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeta.Marshal(b, m, deterministic)
}
func (m *ListMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeta.Merge(m, src)
}
func (m *ListMeta) XXX_Size() int {
	return xxx_messageInfo_ListMeta.Size(m)
}
func (m *ListMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeta proto.InternalMessageInfo

func (m *ListMeta) GetContinue() string {
	if m != nil {
		return m.Continue
	}
	return ""
}

func (m *ListMeta) GetResourceVersion() string {
	if m != nil {
		return m.ResourceVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*ObjectMeta)(nil), "kubecarrier.api.v1.ObjectMeta")
	proto.RegisterMapType((map[string]string)(nil), "kubecarrier.api.v1.ObjectMeta.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "kubecarrier.api.v1.ObjectMeta.LabelsEntry")
	proto.RegisterType((*ListMeta)(nil), "kubecarrier.api.v1.ListMeta")
}

func init() {
	proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc)
}

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6b, 0xea, 0x40,
	0x10, 0xc7, 0xc9, 0x0f, 0x7d, 0xbe, 0xc9, 0xe1, 0xf9, 0x96, 0x77, 0x58, 0x72, 0x78, 0x0d, 0x9e,
	0x42, 0x0f, 0x2b, 0xda, 0x4b, 0xdb, 0x43, 0xa1, 0x42, 0xa1, 0x07, 0x4b, 0xdb, 0x50, 0x7a, 0xe8,
	0x6d, 0x13, 0xa7, 0xb2, 0x35, 0xd9, 0x95, 0xcd, 0x46, 0xf0, 0xdf, 0xe9, 0x5f, 0x5a, 0xdc, 0x18,
	0xb5, 0x2a, 0x48, 0x6f, 0x33, 0xc3, 0x7c, 0x3f, 0x33, 0x3b, 0xdf, 0x05, 0x28, 0xd0, 0x70, 0x36,
	0xd7, 0xca, 0x28, 0x42, 0x66, 0x55, 0x8a, 0x19, 0xd7, 0x5a, 0xa0, 0x66, 0x7c, 0x2e, 0xd8, 0x62,
	0x10, 0x9e, 0x4d, 0x95, 0x9a, 0xe6, 0xd8, 0xb7, 0x1d, 0x69, 0xf5, 0xde, 0x37, 0xa2, 0xc0, 0xd2,
	0xf0, 0x62, 0x5e, 0x8b, 0x7a, 0x9f, 0x3e, 0xc0, 0x63, 0xfa, 0x81, 0x99, 0x79, 0x40, 0xc3, 0x49,
	0x17, 0xbc, 0x4a, 0x4c, 0xa8, 0x13, 0x39, 0xf1, 0xef, 0x64, 0x15, 0x12, 0x02, 0xbe, 0xe4, 0x05,
	0x52, 0xd7, 0x96, 0x6c, 0x4c, 0xee, 0xe1, 0x6f, 0xa6, 0x91, 0x1b, 0xa1, 0xe4, 0x4b, 0xc3, 0xa3,
	0x5e, 0xe4, 0xc4, 0xc1, 0x30, 0x64, 0xf5, 0x44, 0xd6, 0x4c, 0x64, 0x9b, 0x8e, 0xe4, 0x50, 0xb4,
	0x22, 0x4d, 0x30, 0xc7, 0xef, 0x24, 0xff, 0x34, 0xe9, 0x40, 0x44, 0x62, 0xf8, 0xa3, 0xb1, 0x54,
	0x95, 0xce, 0xf0, 0x15, 0x75, 0x29, 0x94, 0xa4, 0x2d, 0xbb, 0xf2, 0x7e, 0x99, 0x8c, 0xa0, 0x9d,
	0xf3, 0x14, 0xf3, 0x92, 0xb6, 0x23, 0x2f, 0x0e, 0x86, 0xe7, 0xec, 0xf0, 0x70, 0x6c, 0x7b, 0x13,
	0x36, 0xb6, 0xcd, 0x77, 0xd2, 0xe8, 0x65, 0xb2, 0x56, 0x92, 0x67, 0x08, 0xb8, 0x94, 0xca, 0xd8,
	0xe7, 0x94, 0xf4, 0x97, 0x05, 0xf5, 0x4f, 0x80, 0x6e, 0xb7, 0x8a, 0x9a, 0xb6, 0xcb, 0x20, 0xff,
	0x01, 0xa6, 0x28, 0x51, 0xdb, 0x94, 0x76, 0x22, 0x27, 0xf6, 0x92, 0x9d, 0x4a, 0x78, 0x05, 0xc1,
	0xce, 0x26, 0x2b, 0xa7, 0x66, 0xb8, 0x6c, 0x9c, 0x9a, 0xe1, 0x92, 0xfc, 0x83, 0xd6, 0x82, 0xe7,
	0x55, 0x63, 0x55, 0x9d, 0x5c, 0xbb, 0x97, 0x4e, 0x78, 0x03, 0xdd, 0xfd, 0xd9, 0x3f, 0xd1, 0xf7,
	0x9e, 0xa0, 0x33, 0x16, 0x65, 0xfd, 0x43, 0x42, 0xe8, 0x64, 0x4a, 0x1a, 0x21, 0x2b, 0x5c, 0x8b,
	0x37, 0xf9, 0x31, 0x0f, 0xdc, 0xa3, 0x1e, 0x8c, 0xfc, 0x37, 0x77, 0x31, 0x48, 0xdb, 0xd6, 0xda,
	0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x7a, 0xcb, 0x53, 0xc6, 0x02, 0x00, 0x00,
}
