/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: offering.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Offering struct {
	Metadata             *ObjectMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *OfferingSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Offering) Reset()         { *m = Offering{} }
func (m *Offering) String() string { return proto.CompactTextString(m) }
func (*Offering) ProtoMessage()    {}
func (*Offering) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{0}
}

func (m *Offering) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offering.Unmarshal(m, b)
}
func (m *Offering) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offering.Marshal(b, m, deterministic)
}
func (m *Offering) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offering.Merge(m, src)
}
func (m *Offering) XXX_Size() int {
	return xxx_messageInfo_Offering.Size(m)
}
func (m *Offering) XXX_DiscardUnknown() {
	xxx_messageInfo_Offering.DiscardUnknown(m)
}

var xxx_messageInfo_Offering proto.InternalMessageInfo

func (m *Offering) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Offering) GetSpec() *OfferingSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type OfferingSpec struct {
	Metadata             *OfferingMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider             *ObjectReference  `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Crd                  *CRDInformation   `protobuf:"bytes,3,opt,name=crd,proto3" json:"crd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OfferingSpec) Reset()         { *m = OfferingSpec{} }
func (m *OfferingSpec) String() string { return proto.CompactTextString(m) }
func (*OfferingSpec) ProtoMessage()    {}
func (*OfferingSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{1}
}

func (m *OfferingSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingSpec.Unmarshal(m, b)
}
func (m *OfferingSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingSpec.Marshal(b, m, deterministic)
}
func (m *OfferingSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingSpec.Merge(m, src)
}
func (m *OfferingSpec) XXX_Size() int {
	return xxx_messageInfo_OfferingSpec.Size(m)
}
func (m *OfferingSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingSpec.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingSpec proto.InternalMessageInfo

func (m *OfferingSpec) GetMetadata() *OfferingMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *OfferingSpec) GetProvider() *ObjectReference {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *OfferingSpec) GetCrd() *CRDInformation {
	if m != nil {
		return m.Crd
	}
	return nil
}

type OfferingMetadata struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferingMetadata) Reset()         { *m = OfferingMetadata{} }
func (m *OfferingMetadata) String() string { return proto.CompactTextString(m) }
func (*OfferingMetadata) ProtoMessage()    {}
func (*OfferingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{2}
}

func (m *OfferingMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingMetadata.Unmarshal(m, b)
}
func (m *OfferingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingMetadata.Marshal(b, m, deterministic)
}
func (m *OfferingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingMetadata.Merge(m, src)
}
func (m *OfferingMetadata) XXX_Size() int {
	return xxx_messageInfo_OfferingMetadata.Size(m)
}
func (m *OfferingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingMetadata proto.InternalMessageInfo

func (m *OfferingMetadata) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *OfferingMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OfferingList struct {
	Metadata             *ListMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Offering `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OfferingList) Reset()         { *m = OfferingList{} }
func (m *OfferingList) String() string { return proto.CompactTextString(m) }
func (*OfferingList) ProtoMessage()    {}
func (*OfferingList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{3}
}

func (m *OfferingList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingList.Unmarshal(m, b)
}
func (m *OfferingList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingList.Marshal(b, m, deterministic)
}
func (m *OfferingList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingList.Merge(m, src)
}
func (m *OfferingList) XXX_Size() int {
	return xxx_messageInfo_OfferingList.Size(m)
}
func (m *OfferingList) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingList.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingList proto.InternalMessageInfo

func (m *OfferingList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *OfferingList) GetItems() []*Offering {
	if m != nil {
		return m.Items
	}
	return nil
}

type OfferingGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferingGetRequest) Reset()         { *m = OfferingGetRequest{} }
func (m *OfferingGetRequest) String() string { return proto.CompactTextString(m) }
func (*OfferingGetRequest) ProtoMessage()    {}
func (*OfferingGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{4}
}

func (m *OfferingGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingGetRequest.Unmarshal(m, b)
}
func (m *OfferingGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingGetRequest.Marshal(b, m, deterministic)
}
func (m *OfferingGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingGetRequest.Merge(m, src)
}
func (m *OfferingGetRequest) XXX_Size() int {
	return xxx_messageInfo_OfferingGetRequest.Size(m)
}
func (m *OfferingGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingGetRequest proto.InternalMessageInfo

func (m *OfferingGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OfferingGetRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type OfferingListRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	LabelSelector        string   `protobuf:"bytes,2,opt,name=labelSelector,proto3" json:"labelSelector,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Continue             string   `protobuf:"bytes,4,opt,name=continue,proto3" json:"continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferingListRequest) Reset()         { *m = OfferingListRequest{} }
func (m *OfferingListRequest) String() string { return proto.CompactTextString(m) }
func (*OfferingListRequest) ProtoMessage()    {}
func (*OfferingListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{5}
}

func (m *OfferingListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingListRequest.Unmarshal(m, b)
}
func (m *OfferingListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingListRequest.Marshal(b, m, deterministic)
}
func (m *OfferingListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingListRequest.Merge(m, src)
}
func (m *OfferingListRequest) XXX_Size() int {
	return xxx_messageInfo_OfferingListRequest.Size(m)
}
func (m *OfferingListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingListRequest proto.InternalMessageInfo

func (m *OfferingListRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *OfferingListRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *OfferingListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *OfferingListRequest) GetContinue() string {
	if m != nil {
		return m.Continue
	}
	return ""
}

func init() {
	proto.RegisterType((*Offering)(nil), "kubecarrier.api.v1.Offering")
	proto.RegisterType((*OfferingSpec)(nil), "kubecarrier.api.v1.OfferingSpec")
	proto.RegisterType((*OfferingMetadata)(nil), "kubecarrier.api.v1.OfferingMetadata")
	proto.RegisterType((*OfferingList)(nil), "kubecarrier.api.v1.OfferingList")
	proto.RegisterType((*OfferingGetRequest)(nil), "kubecarrier.api.v1.OfferingGetRequest")
	proto.RegisterType((*OfferingListRequest)(nil), "kubecarrier.api.v1.OfferingListRequest")
}

func init() {
	proto.RegisterFile("offering.proto", fileDescriptor_d876d3a4bab4c43a)
}

var fileDescriptor_d876d3a4bab4c43a = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0x7e, 0x0a, 0x61, 0xc2, 0x9f, 0x06, 0x0e, 0x56, 0x54, 0x21, 0x6b, 0xa9, 0x68, 0xb9,
	0xc4, 0x4a, 0xe8, 0x01, 0x71, 0x01, 0x15, 0xa4, 0x0a, 0x89, 0x52, 0x69, 0x2b, 0x71, 0xe0, 0xb6,
	0xd9, 0x4c, 0xa2, 0x05, 0x67, 0xd7, 0xac, 0x37, 0x96, 0xaa, 0xa4, 0x17, 0x2e, 0x5c, 0xb8, 0xf1,
	0x50, 0x3c, 0x00, 0xaf, 0xc0, 0x83, 0x54, 0xde, 0xd8, 0x89, 0xdb, 0xa4, 0xe9, 0x6d, 0x66, 0xfc,
	0x7d, 0x33, 0xdf, 0x7c, 0x63, 0x1b, 0x1e, 0x9a, 0xd1, 0x88, 0xac, 0xd2, 0xe3, 0x6e, 0x62, 0x8d,
	0x33, 0x88, 0xdf, 0xa7, 0x03, 0x92, 0xc2, 0x5a, 0x45, 0xb6, 0x2b, 0x12, 0xd5, 0xcd, 0x7a, 0x9d,
	0xdd, 0xb1, 0x31, 0xe3, 0x98, 0x22, 0x91, 0xa8, 0x48, 0x68, 0x6d, 0x9c, 0x70, 0xca, 0xe8, 0x74,
	0xc1, 0xe8, 0xb4, 0xdd, 0x79, 0x42, 0x65, 0x02, 0x13, 0x72, 0x62, 0x11, 0xb3, 0x39, 0xb4, 0x4e,
	0x8b, 0xe6, 0xf8, 0x06, 0x5a, 0xf9, 0x93, 0xa1, 0x70, 0x22, 0xa8, 0x85, 0xb5, 0x83, 0x76, 0xff,
	0x59, 0x77, 0x7d, 0x52, 0xf7, 0x74, 0xf0, 0x8d, 0xa4, 0x3b, 0x21, 0x27, 0xf8, 0x12, 0x8f, 0x87,
	0xd0, 0x4c, 0x13, 0x92, 0x41, 0xdd, 0xf3, 0xc2, 0x8d, 0xbc, 0x62, 0xce, 0x59, 0x42, 0x92, 0x7b,
	0x34, 0xfb, 0x5b, 0x83, 0xfb, 0xd5, 0x32, 0xbe, 0x5b, 0x93, 0xb0, 0xb7, 0xad, 0xd5, 0x49, 0x81,
	0xad, 0x08, 0x79, 0x0b, 0xad, 0xc4, 0x9a, 0x4c, 0x0d, 0xc9, 0x16, 0x62, 0x9e, 0xdf, 0xbc, 0x04,
	0xa7, 0x11, 0x59, 0xd2, 0x92, 0xf8, 0x92, 0x84, 0x87, 0xd0, 0x90, 0x76, 0x18, 0x34, 0x3c, 0x97,
	0x6d, 0xe2, 0xbe, 0xe7, 0x1f, 0x3e, 0xea, 0x91, 0xb1, 0x13, 0x6f, 0x31, 0xcf, 0xe1, 0xec, 0x0b,
	0x3c, 0xbe, 0x2e, 0x0a, 0x43, 0x68, 0x0f, 0x55, 0x9a, 0xc4, 0xe2, 0xfc, 0xb3, 0x98, 0x90, 0xdf,
	0xe7, 0x1e, 0xaf, 0x96, 0x3c, 0x82, 0x52, 0x69, 0x55, 0x92, 0x77, 0xf2, 0x7a, 0x73, 0xc4, 0xaa,
	0xc4, 0xe6, 0x2b, 0x83, 0x3e, 0xa9, 0xd4, 0xe1, 0xeb, 0x35, 0x83, 0x76, 0x37, 0x49, 0xcc, 0xb1,
	0xd7, 0x2e, 0xd4, 0x87, 0x1d, 0xe5, 0x68, 0x92, 0x06, 0xf5, 0xb0, 0x71, 0x13, 0xad, 0x1c, 0xc5,
	0x17, 0x50, 0x76, 0x04, 0x58, 0x96, 0x8e, 0xc9, 0x71, 0xfa, 0x31, 0xa5, 0xd4, 0x21, 0x42, 0x53,
	0xaf, 0x16, 0xf2, 0x31, 0x06, 0x70, 0x57, 0x48, 0x69, 0xa6, 0xda, 0x15, 0x5b, 0x94, 0x29, 0xfb,
	0x55, 0x83, 0x27, 0xd5, 0x15, 0xca, 0x2e, 0x15, 0x46, 0xed, 0x0a, 0x03, 0xf7, 0xe0, 0x41, 0x2c,
	0x06, 0x14, 0x9f, 0x51, 0x4c, 0xd2, 0x19, 0x5b, 0x74, 0xbc, 0x5a, 0xc4, 0xa7, 0xb0, 0x13, 0xab,
	0x89, 0x72, 0xfe, 0x52, 0x0d, 0xbe, 0x48, 0xb0, 0x03, 0x2d, 0x69, 0xb4, 0x53, 0x7a, 0x4a, 0x41,
	0xd3, 0xd3, 0x96, 0x79, 0xff, 0x77, 0x1d, 0x1e, 0x2d, 0xdf, 0x36, 0xb2, 0x99, 0x92, 0x84, 0x33,
	0x68, 0x7a, 0x5f, 0xf7, 0xb7, 0xd9, 0x51, 0x91, 0xdd, 0x09, 0x6f, 0x03, 0xb2, 0x83, 0x9f, 0xff,
	0xfe, 0xff, 0xa9, 0x33, 0x0c, 0xa3, 0xac, 0x17, 0x15, 0x3b, 0xa5, 0xd1, 0xac, 0x88, 0x2e, 0xa2,
	0xf2, 0x63, 0x4e, 0x71, 0x0e, 0x8d, 0x63, 0x72, 0xf8, 0x62, 0x5b, 0xcb, 0x95, 0xef, 0x9d, 0xad,
	0x27, 0x63, 0x91, 0x1f, 0xfb, 0x12, 0xf7, 0x6f, 0x1b, 0x1b, 0xcd, 0xf2, 0x8b, 0x5d, 0x1c, 0x35,
	0xbf, 0xd6, 0xb3, 0xde, 0xe0, 0x8e, 0xff, 0x0f, 0xbc, 0xba, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x86,
	0x3d, 0xeb, 0x06, 0x64, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OfferingServiceClient is the client API for OfferingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OfferingServiceClient interface {
	List(ctx context.Context, in *OfferingListRequest, opts ...grpc.CallOption) (*OfferingList, error)
	Get(ctx context.Context, in *OfferingGetRequest, opts ...grpc.CallOption) (*Offering, error)
}

type offeringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfferingServiceClient(cc grpc.ClientConnInterface) OfferingServiceClient {
	return &offeringServiceClient{cc}
}

func (c *offeringServiceClient) List(ctx context.Context, in *OfferingListRequest, opts ...grpc.CallOption) (*OfferingList, error) {
	out := new(OfferingList)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.OfferingService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offeringServiceClient) Get(ctx context.Context, in *OfferingGetRequest, opts ...grpc.CallOption) (*Offering, error) {
	out := new(Offering)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.OfferingService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfferingServiceServer is the server API for OfferingService service.
type OfferingServiceServer interface {
	List(context.Context, *OfferingListRequest) (*OfferingList, error)
	Get(context.Context, *OfferingGetRequest) (*Offering, error)
}

// UnimplementedOfferingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOfferingServiceServer struct {
}

func (*UnimplementedOfferingServiceServer) List(ctx context.Context, req *OfferingListRequest) (*OfferingList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedOfferingServiceServer) Get(ctx context.Context, req *OfferingGetRequest) (*Offering, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterOfferingServiceServer(s *grpc.Server, srv OfferingServiceServer) {
	s.RegisterService(&_OfferingService_serviceDesc, srv)
}

func _OfferingService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferingServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.OfferingService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferingServiceServer).List(ctx, req.(*OfferingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferingService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferingGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferingServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.OfferingService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferingServiceServer).Get(ctx, req.(*OfferingGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OfferingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.OfferingService",
	HandlerType: (*OfferingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _OfferingService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OfferingService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offering.proto",
}
