/*
Copyright 2021 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: offering.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Offering struct {
	Metadata             *ObjectMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *OfferingSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Offering) Reset()         { *m = Offering{} }
func (m *Offering) String() string { return proto.CompactTextString(m) }
func (*Offering) ProtoMessage()    {}
func (*Offering) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{0}
}

func (m *Offering) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offering.Unmarshal(m, b)
}
func (m *Offering) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offering.Marshal(b, m, deterministic)
}
func (m *Offering) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offering.Merge(m, src)
}
func (m *Offering) XXX_Size() int {
	return xxx_messageInfo_Offering.Size(m)
}
func (m *Offering) XXX_DiscardUnknown() {
	xxx_messageInfo_Offering.DiscardUnknown(m)
}

var xxx_messageInfo_Offering proto.InternalMessageInfo

func (m *Offering) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Offering) GetSpec() *OfferingSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type OfferingSpec struct {
	Metadata             *OfferingMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider             *ObjectReference  `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Crd                  *CRDInformation   `protobuf:"bytes,3,opt,name=crd,proto3" json:"crd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OfferingSpec) Reset()         { *m = OfferingSpec{} }
func (m *OfferingSpec) String() string { return proto.CompactTextString(m) }
func (*OfferingSpec) ProtoMessage()    {}
func (*OfferingSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{1}
}

func (m *OfferingSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingSpec.Unmarshal(m, b)
}
func (m *OfferingSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingSpec.Marshal(b, m, deterministic)
}
func (m *OfferingSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingSpec.Merge(m, src)
}
func (m *OfferingSpec) XXX_Size() int {
	return xxx_messageInfo_OfferingSpec.Size(m)
}
func (m *OfferingSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingSpec.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingSpec proto.InternalMessageInfo

func (m *OfferingSpec) GetMetadata() *OfferingMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *OfferingSpec) GetProvider() *ObjectReference {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *OfferingSpec) GetCrd() *CRDInformation {
	if m != nil {
		return m.Crd
	}
	return nil
}

type OfferingMetadata struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription     string   `protobuf:"bytes,3,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Logo                 *Image   `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Icon                 *Image   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferingMetadata) Reset()         { *m = OfferingMetadata{} }
func (m *OfferingMetadata) String() string { return proto.CompactTextString(m) }
func (*OfferingMetadata) ProtoMessage()    {}
func (*OfferingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{2}
}

func (m *OfferingMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingMetadata.Unmarshal(m, b)
}
func (m *OfferingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingMetadata.Marshal(b, m, deterministic)
}
func (m *OfferingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingMetadata.Merge(m, src)
}
func (m *OfferingMetadata) XXX_Size() int {
	return xxx_messageInfo_OfferingMetadata.Size(m)
}
func (m *OfferingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingMetadata proto.InternalMessageInfo

func (m *OfferingMetadata) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *OfferingMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OfferingMetadata) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *OfferingMetadata) GetLogo() *Image {
	if m != nil {
		return m.Logo
	}
	return nil
}

func (m *OfferingMetadata) GetIcon() *Image {
	if m != nil {
		return m.Icon
	}
	return nil
}

type OfferingList struct {
	Metadata             *ListMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Offering `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OfferingList) Reset()         { *m = OfferingList{} }
func (m *OfferingList) String() string { return proto.CompactTextString(m) }
func (*OfferingList) ProtoMessage()    {}
func (*OfferingList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d876d3a4bab4c43a, []int{3}
}

func (m *OfferingList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferingList.Unmarshal(m, b)
}
func (m *OfferingList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferingList.Marshal(b, m, deterministic)
}
func (m *OfferingList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferingList.Merge(m, src)
}
func (m *OfferingList) XXX_Size() int {
	return xxx_messageInfo_OfferingList.Size(m)
}
func (m *OfferingList) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferingList.DiscardUnknown(m)
}

var xxx_messageInfo_OfferingList proto.InternalMessageInfo

func (m *OfferingList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *OfferingList) GetItems() []*Offering {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Offering)(nil), "kubecarrier.api.v1.Offering")
	proto.RegisterType((*OfferingSpec)(nil), "kubecarrier.api.v1.OfferingSpec")
	proto.RegisterType((*OfferingMetadata)(nil), "kubecarrier.api.v1.OfferingMetadata")
	proto.RegisterType((*OfferingList)(nil), "kubecarrier.api.v1.OfferingList")
}

func init() {
	proto.RegisterFile("offering.proto", fileDescriptor_d876d3a4bab4c43a)
}

var fileDescriptor_d876d3a4bab4c43a = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdf, 0x6e, 0xd3, 0x3c,
	0x18, 0xc6, 0xd5, 0x24, 0xfd, 0xd4, 0xcf, 0xe5, 0xcf, 0xe4, 0xa3, 0x50, 0x4d, 0x23, 0x0a, 0x08,
	0x0a, 0x12, 0x09, 0x2d, 0x3b, 0x40, 0x9c, 0x80, 0x60, 0x68, 0x9a, 0xc4, 0x98, 0x64, 0x0e, 0x90,
	0x38, 0x73, 0xdd, 0xb7, 0x99, 0xa1, 0xb1, 0x83, 0xed, 0x06, 0x4d, 0xdd, 0x4e, 0xb8, 0x05, 0x2e,
	0x8a, 0x0b, 0xe0, 0x06, 0x38, 0xe0, 0x26, 0x38, 0x43, 0x76, 0x93, 0xae, 0x5a, 0xd3, 0xee, 0xac,
	0x7e, 0xf3, 0x7b, 0xfc, 0x3c, 0x6f, 0xfd, 0xda, 0xe8, 0x96, 0x9c, 0x4c, 0x40, 0x71, 0x91, 0x25,
	0x85, 0x92, 0x46, 0x62, 0xfc, 0x65, 0x36, 0x02, 0x46, 0x95, 0xe2, 0xa0, 0x12, 0x5a, 0xf0, 0xa4,
	0x1c, 0xf4, 0x76, 0x33, 0x29, 0xb3, 0x29, 0xa4, 0xb4, 0xe0, 0x29, 0x15, 0x42, 0x1a, 0x6a, 0xb8,
	0x14, 0x7a, 0xa1, 0xe8, 0x75, 0xcd, 0x59, 0x01, 0xf5, 0x02, 0xe5, 0x60, 0x68, 0xfd, 0x01, 0x4a,
	0x10, 0xa6, 0x5a, 0xdc, 0x54, 0xf0, 0x75, 0x06, 0xba, 0x5a, 0xc6, 0xe7, 0xa8, 0x73, 0x52, 0x19,
	0xe3, 0x17, 0xa8, 0x63, 0x55, 0x63, 0x6a, 0x68, 0xd8, 0x8a, 0x5a, 0xfd, 0xee, 0x70, 0x2f, 0x59,
	0x4f, 0x91, 0x9c, 0x8c, 0x3e, 0x03, 0x33, 0xc7, 0x60, 0x28, 0x59, 0xf2, 0x78, 0x1f, 0x05, 0xba,
	0x00, 0x16, 0x7a, 0x4e, 0x17, 0x35, 0xea, 0x2a, 0x9f, 0x0f, 0x05, 0x30, 0xe2, 0xe8, 0xf8, 0x67,
	0x0b, 0xdd, 0x58, 0x2d, 0xe3, 0x57, 0x6b, 0x11, 0xee, 0x6f, 0xdb, 0xea, 0xb8, 0x62, 0x57, 0x82,
	0xbc, 0x44, 0x9d, 0x42, 0xc9, 0x92, 0x8f, 0x41, 0x55, 0x61, 0xee, 0x6d, 0x6e, 0x82, 0xc0, 0x04,
	0x14, 0x08, 0x06, 0x64, 0x29, 0xc2, 0xfb, 0xc8, 0x67, 0x6a, 0x1c, 0xfa, 0x4e, 0x1b, 0x37, 0x69,
	0xdf, 0x90, 0x83, 0x23, 0x31, 0x91, 0x2a, 0x77, 0x7f, 0x3f, 0xb1, 0x78, 0xfc, 0xbb, 0x85, 0x76,
	0xae, 0xa6, 0xc2, 0x11, 0xea, 0x8e, 0xb9, 0x2e, 0xa6, 0xf4, 0xec, 0x3d, 0xcd, 0xc1, 0x35, 0xf4,
	0x3f, 0x59, 0x2d, 0x39, 0x02, 0x34, 0x53, 0xbc, 0xb0, 0x5b, 0xb9, 0xc0, 0x96, 0xb8, 0x2c, 0xe1,
	0xc7, 0x68, 0x47, 0x9f, 0x4a, 0x65, 0x0e, 0x56, 0x30, 0xdf, 0x61, 0x6b, 0x75, 0xfc, 0x04, 0x05,
	0x53, 0x99, 0xc9, 0x30, 0x70, 0xd9, 0xef, 0x34, 0x65, 0x3f, 0xca, 0x69, 0x06, 0xc4, 0x61, 0x16,
	0xe7, 0x4c, 0x8a, 0xb0, 0x7d, 0x2d, 0x6e, 0xb1, 0xf8, 0xfc, 0xf2, 0xac, 0xde, 0x71, 0x6d, 0xf0,
	0xf3, 0xb5, 0xb3, 0xda, 0x6d, 0xda, 0xc2, 0xb2, 0x57, 0x86, 0x65, 0x88, 0xda, 0xdc, 0x40, 0xae,
	0x43, 0x2f, 0xf2, 0x37, 0xc9, 0x6a, 0x2b, 0xb2, 0x40, 0x87, 0x7f, 0x3d, 0x74, 0x7b, 0x39, 0x2a,
	0xa0, 0x4a, 0xce, 0x00, 0x6b, 0x14, 0xb8, 0x24, 0x77, 0x37, 0xf9, 0x92, 0xc5, 0xac, 0xf7, 0xb6,
	0xce, 0xa3, 0x05, 0xe3, 0xfe, 0xf7, 0x5f, 0x7f, 0x7e, 0x78, 0x31, 0x8e, 0xd2, 0x72, 0x90, 0x52,
	0xc6, 0xe4, 0x4c, 0x18, 0x9d, 0xce, 0xab, 0x5f, 0x17, 0x69, 0x7d, 0x3b, 0x35, 0x36, 0xc8, 0x3f,
	0x04, 0x83, 0x1b, 0xaf, 0xc6, 0x21, 0x2c, 0x2d, 0xb7, 0x36, 0x15, 0xa7, 0xce, 0xee, 0x11, 0x7e,
	0x78, 0x9d, 0x5d, 0x3a, 0x17, 0x34, 0x87, 0x0b, 0x3c, 0x47, 0xed, 0x8f, 0xd4, 0xb0, 0x53, 0xdc,
	0xd8, 0x8a, 0xfb, 0x54, 0x3b, 0xef, 0x6d, 0x24, 0xde, 0xda, 0x77, 0x20, 0x4e, 0x9c, 0x77, 0x1f,
	0x3f, 0xb0, 0xde, 0xdf, 0x6c, 0x7d, 0x6b, 0x82, 0xa7, 0xad, 0xd7, 0xc1, 0x27, 0xaf, 0x1c, 0x8c,
	0xfe, 0x73, 0x2f, 0xc6, 0xb3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x91, 0xd7, 0x9c, 0x7e, 0xaa,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OfferingServiceClient is the client API for OfferingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OfferingServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*OfferingList, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Offering, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (OfferingService_WatchClient, error)
}

type offeringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfferingServiceClient(cc grpc.ClientConnInterface) OfferingServiceClient {
	return &offeringServiceClient{cc}
}

func (c *offeringServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*OfferingList, error) {
	out := new(OfferingList)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.OfferingService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offeringServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Offering, error) {
	out := new(Offering)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.OfferingService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offeringServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (OfferingService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OfferingService_serviceDesc.Streams[0], "/kubecarrier.api.v1.OfferingService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &offeringServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OfferingService_WatchClient interface {
	Recv() (*WatchEvent, error)
	grpc.ClientStream
}

type offeringServiceWatchClient struct {
	grpc.ClientStream
}

func (x *offeringServiceWatchClient) Recv() (*WatchEvent, error) {
	m := new(WatchEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OfferingServiceServer is the server API for OfferingService service.
type OfferingServiceServer interface {
	List(context.Context, *ListRequest) (*OfferingList, error)
	Get(context.Context, *GetRequest) (*Offering, error)
	Watch(*WatchRequest, OfferingService_WatchServer) error
}

// UnimplementedOfferingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOfferingServiceServer struct {
}

func (*UnimplementedOfferingServiceServer) List(ctx context.Context, req *ListRequest) (*OfferingList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedOfferingServiceServer) Get(ctx context.Context, req *GetRequest) (*Offering, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedOfferingServiceServer) Watch(req *WatchRequest, srv OfferingService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterOfferingServiceServer(s *grpc.Server, srv OfferingServiceServer) {
	s.RegisterService(&_OfferingService_serviceDesc, srv)
}

func _OfferingService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferingServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.OfferingService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferingServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferingService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferingServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.OfferingService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferingServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferingService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OfferingServiceServer).Watch(m, &offeringServiceWatchServer{stream})
}

type OfferingService_WatchServer interface {
	Send(*WatchEvent) error
	grpc.ServerStream
}

type offeringServiceWatchServer struct {
	grpc.ServerStream
}

func (x *offeringServiceWatchServer) Send(m *WatchEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _OfferingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.OfferingService",
	HandlerType: (*OfferingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _OfferingService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OfferingService_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _OfferingService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "offering.proto",
}
