/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Provider struct {
	Metadata             *ObjectMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *ProviderSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{0}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Provider) GetSpec() *ProviderSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type ProviderSpec struct {
	Metadata             *ProviderMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProviderSpec) Reset()         { *m = ProviderSpec{} }
func (m *ProviderSpec) String() string { return proto.CompactTextString(m) }
func (*ProviderSpec) ProtoMessage()    {}
func (*ProviderSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{1}
}

func (m *ProviderSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderSpec.Unmarshal(m, b)
}
func (m *ProviderSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderSpec.Marshal(b, m, deterministic)
}
func (m *ProviderSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderSpec.Merge(m, src)
}
func (m *ProviderSpec) XXX_Size() int {
	return xxx_messageInfo_ProviderSpec.Size(m)
}
func (m *ProviderSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderSpec proto.InternalMessageInfo

func (m *ProviderSpec) GetMetadata() *ProviderMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ProviderList struct {
	Metadata             *ListMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Provider `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProviderList) Reset()         { *m = ProviderList{} }
func (m *ProviderList) String() string { return proto.CompactTextString(m) }
func (*ProviderList) ProtoMessage()    {}
func (*ProviderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{2}
}

func (m *ProviderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderList.Unmarshal(m, b)
}
func (m *ProviderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderList.Marshal(b, m, deterministic)
}
func (m *ProviderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderList.Merge(m, src)
}
func (m *ProviderList) XXX_Size() int {
	return xxx_messageInfo_ProviderList.Size(m)
}
func (m *ProviderList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderList.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderList proto.InternalMessageInfo

func (m *ProviderList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ProviderList) GetItems() []*Provider {
	if m != nil {
		return m.Items
	}
	return nil
}

type ProviderGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderGetRequest) Reset()         { *m = ProviderGetRequest{} }
func (m *ProviderGetRequest) String() string { return proto.CompactTextString(m) }
func (*ProviderGetRequest) ProtoMessage()    {}
func (*ProviderGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{3}
}

func (m *ProviderGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderGetRequest.Unmarshal(m, b)
}
func (m *ProviderGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderGetRequest.Marshal(b, m, deterministic)
}
func (m *ProviderGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderGetRequest.Merge(m, src)
}
func (m *ProviderGetRequest) XXX_Size() int {
	return xxx_messageInfo_ProviderGetRequest.Size(m)
}
func (m *ProviderGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderGetRequest proto.InternalMessageInfo

func (m *ProviderGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProviderGetRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type ProviderListRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	LabelSelector        string   `protobuf:"bytes,2,opt,name=labelSelector,proto3" json:"labelSelector,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Continue             string   `protobuf:"bytes,4,opt,name=continue,proto3" json:"continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderListRequest) Reset()         { *m = ProviderListRequest{} }
func (m *ProviderListRequest) String() string { return proto.CompactTextString(m) }
func (*ProviderListRequest) ProtoMessage()    {}
func (*ProviderListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{4}
}

func (m *ProviderListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderListRequest.Unmarshal(m, b)
}
func (m *ProviderListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderListRequest.Marshal(b, m, deterministic)
}
func (m *ProviderListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderListRequest.Merge(m, src)
}
func (m *ProviderListRequest) XXX_Size() int {
	return xxx_messageInfo_ProviderListRequest.Size(m)
}
func (m *ProviderListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderListRequest proto.InternalMessageInfo

func (m *ProviderListRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ProviderListRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *ProviderListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ProviderListRequest) GetContinue() string {
	if m != nil {
		return m.Continue
	}
	return ""
}

type ProviderMetadata struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription     string   `protobuf:"bytes,3,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Logo                 *Image   `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Icon                 *Image   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderMetadata) Reset()         { *m = ProviderMetadata{} }
func (m *ProviderMetadata) String() string { return proto.CompactTextString(m) }
func (*ProviderMetadata) ProtoMessage()    {}
func (*ProviderMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a9f3c02af3d1c8, []int{5}
}

func (m *ProviderMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderMetadata.Unmarshal(m, b)
}
func (m *ProviderMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderMetadata.Marshal(b, m, deterministic)
}
func (m *ProviderMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderMetadata.Merge(m, src)
}
func (m *ProviderMetadata) XXX_Size() int {
	return xxx_messageInfo_ProviderMetadata.Size(m)
}
func (m *ProviderMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderMetadata proto.InternalMessageInfo

func (m *ProviderMetadata) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ProviderMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProviderMetadata) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *ProviderMetadata) GetLogo() *Image {
	if m != nil {
		return m.Logo
	}
	return nil
}

func (m *ProviderMetadata) GetIcon() *Image {
	if m != nil {
		return m.Icon
	}
	return nil
}

func init() {
	proto.RegisterType((*Provider)(nil), "kubecarrier.api.v1.Provider")
	proto.RegisterType((*ProviderSpec)(nil), "kubecarrier.api.v1.ProviderSpec")
	proto.RegisterType((*ProviderList)(nil), "kubecarrier.api.v1.ProviderList")
	proto.RegisterType((*ProviderGetRequest)(nil), "kubecarrier.api.v1.ProviderGetRequest")
	proto.RegisterType((*ProviderListRequest)(nil), "kubecarrier.api.v1.ProviderListRequest")
	proto.RegisterType((*ProviderMetadata)(nil), "kubecarrier.api.v1.ProviderMetadata")
}

func init() {
	proto.RegisterFile("provider.proto", fileDescriptor_c6a9f3c02af3d1c8)
}

var fileDescriptor_c6a9f3c02af3d1c8 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xc4, 0x85, 0x74, 0xc2, 0x9f, 0x6a, 0xe0, 0x60, 0xa2, 0x0a, 0x59, 0x56, 0x45,
	0x03, 0x12, 0xb6, 0x12, 0x38, 0x20, 0x4e, 0xa8, 0x42, 0xaa, 0x90, 0x28, 0x54, 0xee, 0x8d, 0xdb,
	0x66, 0x33, 0x0a, 0x0b, 0xb6, 0xd7, 0xec, 0x6e, 0x2c, 0x55, 0x49, 0x2f, 0x5c, 0xb8, 0x70, 0xe3,
	0xd1, 0x78, 0x01, 0x0e, 0x3c, 0x08, 0xf2, 0xc6, 0x4e, 0xdc, 0x26, 0x24, 0xb7, 0xdd, 0xc9, 0xef,
	0xfb, 0x66, 0x66, 0x67, 0x62, 0xb8, 0x97, 0x2b, 0x59, 0x88, 0x31, 0xa9, 0x30, 0x57, 0xd2, 0x48,
	0xc4, 0xaf, 0xd3, 0x11, 0x71, 0xa6, 0x94, 0x20, 0x15, 0xb2, 0x5c, 0x84, 0xc5, 0xa0, 0x77, 0x38,
	0x91, 0x72, 0x92, 0x50, 0xc4, 0x72, 0x11, 0xb1, 0x2c, 0x93, 0x86, 0x19, 0x21, 0x33, 0xbd, 0x50,
	0xf4, 0x20, 0x25, 0xc3, 0xaa, 0x73, 0xd7, 0x5c, 0xe6, 0x54, 0xfd, 0x10, 0xcc, 0xa1, 0x73, 0x5e,
	0x99, 0xe3, 0x6b, 0xe8, 0x94, 0xd8, 0x98, 0x19, 0xe6, 0x39, 0xbe, 0xd3, 0xef, 0x0e, 0x1f, 0x87,
	0xeb, 0x99, 0xc2, 0x8f, 0xa3, 0x2f, 0xc4, 0xcd, 0x19, 0x19, 0x16, 0x2f, 0x79, 0x7c, 0x09, 0xae,
	0xce, 0x89, 0x7b, 0x2d, 0xab, 0xf3, 0x37, 0xe9, 0xea, 0x3c, 0x17, 0x39, 0xf1, 0xd8, 0xd2, 0xc1,
	0x39, 0xdc, 0x69, 0x46, 0xf1, 0xcd, 0x5a, 0x05, 0x47, 0xdb, 0x9c, 0xce, 0x2a, 0x76, 0x55, 0x47,
	0x30, 0x5f, 0x39, 0xbe, 0x17, 0xda, 0xe0, 0xab, 0x35, 0xc7, 0xc3, 0x4d, 0x8e, 0x25, 0x7b, 0xa3,
	0xa3, 0x21, 0xec, 0x09, 0x43, 0xa9, 0xf6, 0x5a, 0x7e, 0xfb, 0x7f, 0xb2, 0x3a, 0x55, 0xbc, 0x40,
	0x83, 0x13, 0xc0, 0x3a, 0x74, 0x4a, 0x26, 0xa6, 0x6f, 0x53, 0xd2, 0x06, 0x11, 0xdc, 0x8c, 0xa5,
	0x64, 0xf3, 0xef, 0xc7, 0xf6, 0x8c, 0x1e, 0xdc, 0x66, 0x9c, 0xcb, 0x69, 0x66, 0xec, 0x93, 0xed,
	0xc7, 0xf5, 0x35, 0xf8, 0xe1, 0xc0, 0x83, 0x66, 0x0b, 0xb5, 0x4b, 0x43, 0xe1, 0x5c, 0x53, 0xe0,
	0x11, 0xdc, 0x4d, 0xd8, 0x88, 0x92, 0x0b, 0x4a, 0x88, 0x1b, 0xa9, 0x2a, 0xc7, 0xeb, 0x41, 0x7c,
	0x08, 0x7b, 0x89, 0x48, 0x85, 0xf1, 0xda, 0xbe, 0xd3, 0x6f, 0xc7, 0x8b, 0x0b, 0xf6, 0xa0, 0xc3,
	0x65, 0x66, 0x44, 0x36, 0x25, 0xcf, 0xb5, 0xb2, 0xe5, 0x3d, 0xf8, 0xe3, 0xc0, 0xc1, 0xcd, 0xa7,
	0x46, 0x1f, 0xba, 0x63, 0xa1, 0xf3, 0x84, 0x5d, 0x7e, 0x58, 0xf5, 0xd4, 0x0c, 0x59, 0x82, 0x34,
	0x57, 0x22, 0x2f, 0x37, 0xb0, 0x2a, 0xa6, 0x19, 0xc2, 0x67, 0x70, 0xa0, 0x3f, 0x4b, 0x65, 0xde,
	0x36, 0xb0, 0xb6, 0xc5, 0xd6, 0xe2, 0xf8, 0x1c, 0xdc, 0x44, 0x4e, 0xa4, 0x2d, 0xae, 0x3b, 0x7c,
	0xb4, 0x69, 0x0a, 0xef, 0x52, 0x36, 0xa1, 0xd8, 0x62, 0x25, 0x2e, 0xb8, 0xcc, 0xbc, 0xbd, 0x9d,
	0x78, 0x89, 0x0d, 0x7f, 0xb6, 0xe0, 0xfe, 0x72, 0x03, 0x49, 0x15, 0x82, 0x13, 0xce, 0xc0, 0xb5,
	0xab, 0x73, 0xbc, 0x6d, 0xe2, 0x8d, 0xc9, 0xf4, 0xfc, 0x5d, 0x60, 0xd0, 0xff, 0xfe, 0xfb, 0xef,
	0xaf, 0x56, 0x80, 0x7e, 0x54, 0x0c, 0xa2, 0x6a, 0x6c, 0x3a, 0x9a, 0x55, 0xa7, 0xab, 0xa8, 0xfe,
	0x7f, 0x6b, 0x9c, 0x43, 0xfb, 0x94, 0x0c, 0x3e, 0xd9, 0x66, 0xb9, 0x5a, 0xad, 0xde, 0xd6, 0xad,
	0x0c, 0x22, 0x9b, 0xf6, 0x29, 0x1e, 0xef, 0x4a, 0x1b, 0xcd, 0xca, 0xa5, 0xbc, 0x3a, 0x71, 0x3f,
	0xb5, 0x8a, 0xc1, 0xe8, 0x96, 0xfd, 0x34, 0xbc, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x2a,
	0x31, 0xf4, 0x77, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderServiceClient interface {
	List(ctx context.Context, in *ProviderListRequest, opts ...grpc.CallOption) (*ProviderList, error)
	Get(ctx context.Context, in *ProviderGetRequest, opts ...grpc.CallOption) (*Provider, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) List(ctx context.Context, in *ProviderListRequest, opts ...grpc.CallOption) (*ProviderList, error) {
	out := new(ProviderList)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.ProviderService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Get(ctx context.Context, in *ProviderGetRequest, opts ...grpc.CallOption) (*Provider, error) {
	out := new(Provider)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.ProviderService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
type ProviderServiceServer interface {
	List(context.Context, *ProviderListRequest) (*ProviderList, error)
	Get(context.Context, *ProviderGetRequest) (*Provider, error)
}

// UnimplementedProviderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProviderServiceServer struct {
}

func (*UnimplementedProviderServiceServer) List(ctx context.Context, req *ProviderListRequest) (*ProviderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedProviderServiceServer) Get(ctx context.Context, req *ProviderGetRequest) (*Provider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterProviderServiceServer(s *grpc.Server, srv ProviderServiceServer) {
	s.RegisterService(&_ProviderService_serviceDesc, srv)
}

func _ProviderService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.ProviderService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).List(ctx, req.(*ProviderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.ProviderService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Get(ctx, req.(*ProviderGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProviderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ProviderService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProviderService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider.proto",
}
