/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: region.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Region struct {
	Metadata             *ObjectMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *RegionSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Region) Reset()         { *m = Region{} }
func (m *Region) String() string { return proto.CompactTextString(m) }
func (*Region) ProtoMessage()    {}
func (*Region) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{0}
}

func (m *Region) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Region.Unmarshal(m, b)
}
func (m *Region) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Region.Marshal(b, m, deterministic)
}
func (m *Region) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Region.Merge(m, src)
}
func (m *Region) XXX_Size() int {
	return xxx_messageInfo_Region.Size(m)
}
func (m *Region) XXX_DiscardUnknown() {
	xxx_messageInfo_Region.DiscardUnknown(m)
}

var xxx_messageInfo_Region proto.InternalMessageInfo

func (m *Region) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Region) GetSpec() *RegionSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type RegionSpec struct {
	Metadata             *RegionMetadata  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider             *ObjectReference `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegionSpec) Reset()         { *m = RegionSpec{} }
func (m *RegionSpec) String() string { return proto.CompactTextString(m) }
func (*RegionSpec) ProtoMessage()    {}
func (*RegionSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{1}
}

func (m *RegionSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionSpec.Unmarshal(m, b)
}
func (m *RegionSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionSpec.Marshal(b, m, deterministic)
}
func (m *RegionSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionSpec.Merge(m, src)
}
func (m *RegionSpec) XXX_Size() int {
	return xxx_messageInfo_RegionSpec.Size(m)
}
func (m *RegionSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionSpec.DiscardUnknown(m)
}

var xxx_messageInfo_RegionSpec proto.InternalMessageInfo

func (m *RegionSpec) GetMetadata() *RegionMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *RegionSpec) GetProvider() *ObjectReference {
	if m != nil {
		return m.Provider
	}
	return nil
}

type RegionMetadata struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegionMetadata) Reset()         { *m = RegionMetadata{} }
func (m *RegionMetadata) String() string { return proto.CompactTextString(m) }
func (*RegionMetadata) ProtoMessage()    {}
func (*RegionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{2}
}

func (m *RegionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionMetadata.Unmarshal(m, b)
}
func (m *RegionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionMetadata.Marshal(b, m, deterministic)
}
func (m *RegionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionMetadata.Merge(m, src)
}
func (m *RegionMetadata) XXX_Size() int {
	return xxx_messageInfo_RegionMetadata.Size(m)
}
func (m *RegionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RegionMetadata proto.InternalMessageInfo

func (m *RegionMetadata) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *RegionMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RegionList struct {
	Metadata             *ListMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Region `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegionList) Reset()         { *m = RegionList{} }
func (m *RegionList) String() string { return proto.CompactTextString(m) }
func (*RegionList) ProtoMessage()    {}
func (*RegionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{3}
}

func (m *RegionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionList.Unmarshal(m, b)
}
func (m *RegionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionList.Marshal(b, m, deterministic)
}
func (m *RegionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionList.Merge(m, src)
}
func (m *RegionList) XXX_Size() int {
	return xxx_messageInfo_RegionList.Size(m)
}
func (m *RegionList) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionList.DiscardUnknown(m)
}

var xxx_messageInfo_RegionList proto.InternalMessageInfo

func (m *RegionList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *RegionList) GetItems() []*Region {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Region)(nil), "kubecarrier.api.v1.Region")
	proto.RegisterType((*RegionSpec)(nil), "kubecarrier.api.v1.RegionSpec")
	proto.RegisterType((*RegionMetadata)(nil), "kubecarrier.api.v1.RegionMetadata")
	proto.RegisterType((*RegionList)(nil), "kubecarrier.api.v1.RegionList")
}

func init() {
	proto.RegisterFile("region.proto", fileDescriptor_6eef30384a8831dd)
}

var fileDescriptor_6eef30384a8831dd = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x8e, 0xda, 0x30,
	0x10, 0xc6, 0x95, 0x40, 0x11, 0x75, 0x4a, 0x0f, 0x3e, 0xa1, 0x08, 0xd1, 0x28, 0x55, 0x5b, 0x2e,
	0x4d, 0x4a, 0x7a, 0xa9, 0x7a, 0x68, 0xa5, 0x5e, 0xb8, 0x94, 0x56, 0x72, 0x7b, 0xea, 0xcd, 0x98,
	0x29, 0xf2, 0x2e, 0x89, 0xbd, 0xb6, 0x89, 0x40, 0x88, 0xcb, 0xde, 0xf7, 0xb4, 0x8f, 0xb6, 0xaf,
	0xb0, 0x4f, 0xb0, 0x4f, 0xb0, 0x8a, 0x13, 0xfe, 0xec, 0x42, 0xb8, 0x79, 0x46, 0xdf, 0xcc, 0xef,
	0x9b, 0xf1, 0xa0, 0x57, 0x0a, 0x66, 0x5c, 0x64, 0x91, 0x54, 0xc2, 0x08, 0x8c, 0x2f, 0x17, 0x13,
	0x60, 0x54, 0x29, 0x0e, 0x2a, 0xa2, 0x92, 0x47, 0xf9, 0xd0, 0xef, 0xcd, 0x84, 0x98, 0xcd, 0x21,
	0xa6, 0x92, 0xc7, 0x34, 0xcb, 0x84, 0xa1, 0x86, 0x8b, 0x4c, 0x97, 0x15, 0xbe, 0x67, 0x56, 0x12,
	0xb6, 0x01, 0x4a, 0xc1, 0xd0, 0xea, 0xdd, 0x51, 0x70, 0xb5, 0x00, 0x6d, 0xca, 0x30, 0x5c, 0xa2,
	0x16, 0xb1, 0x24, 0xfc, 0x15, 0xb5, 0x0b, 0xd9, 0x94, 0x1a, 0xda, 0x75, 0x02, 0x67, 0xe0, 0x25,
	0xfd, 0xe8, 0x18, 0x1b, 0xfd, 0x9e, 0x5c, 0x00, 0x33, 0x63, 0x30, 0x94, 0xec, 0xf4, 0x38, 0x41,
	0x4d, 0x2d, 0x81, 0x75, 0xdd, 0xfa, 0xba, 0x92, 0xf2, 0x47, 0x02, 0x23, 0x56, 0x1b, 0xde, 0x38,
	0x08, 0xed, 0x93, 0xf8, 0xdb, 0x11, 0x3e, 0xac, 0x6f, 0x33, 0xae, 0x94, 0x07, 0x16, 0xbe, 0xa3,
	0xb6, 0x54, 0x22, 0xe7, 0x53, 0x50, 0x95, 0x8d, 0xb7, 0xf5, 0xf6, 0x09, 0xfc, 0x07, 0x05, 0x19,
	0x03, 0xb2, 0x2b, 0x0a, 0xff, 0xa2, 0xd7, 0x4f, 0x9b, 0xe3, 0x00, 0x79, 0x53, 0xae, 0xe5, 0x9c,
	0xae, 0x7e, 0xd1, 0x14, 0xac, 0xab, 0x97, 0xe4, 0x30, 0x65, 0x15, 0xa0, 0x99, 0xe2, 0xb2, 0xd8,
	0xbd, 0xe5, 0x16, 0x8a, 0x7d, 0x2a, 0x5c, 0x6e, 0x87, 0xfc, 0xc9, 0xb5, 0xc1, 0x5f, 0x8e, 0x86,
	0xec, 0x9d, 0x32, 0x59, 0x68, 0x9f, 0x6d, 0xf8, 0x13, 0x7a, 0xc1, 0x0d, 0xa4, 0xba, 0xeb, 0x06,
	0x8d, 0x81, 0x97, 0xf8, 0xf5, 0xbb, 0x21, 0xa5, 0x30, 0x79, 0x70, 0x50, 0xa7, 0xda, 0x2f, 0xa8,
	0x9c, 0x33, 0xc0, 0x02, 0x35, 0xad, 0x8b, 0x37, 0x75, 0x4c, 0x52, 0x9e, 0x86, 0x7f, 0xe6, 0x03,
	0x0b, 0x59, 0xf8, 0xfe, 0xfa, 0xee, 0xfe, 0xd6, 0x0d, 0x70, 0x3f, 0xce, 0x87, 0x31, 0x65, 0x4c,
	0x2c, 0x32, 0xa3, 0xe3, 0x75, 0xf5, 0xda, 0xc4, 0xe5, 0xed, 0x6a, 0x2c, 0x51, 0x63, 0x04, 0x06,
	0x9f, 0x6c, 0x37, 0x82, 0x1d, 0xee, 0xcc, 0x30, 0xe1, 0x47, 0x8b, 0xfa, 0x80, 0xdf, 0x9d, 0x47,
	0xc5, 0xeb, 0x8c, 0xa6, 0xb0, 0xf9, 0xd1, 0xfc, 0xe7, 0xe6, 0xc3, 0x49, 0xcb, 0xde, 0xf6, 0xe7,
	0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0x2c, 0x14, 0xa7, 0x45, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RegionServiceClient is the client API for RegionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegionServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*RegionList, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Region, error)
}

type regionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionServiceClient(cc grpc.ClientConnInterface) RegionServiceClient {
	return &regionServiceClient{cc}
}

func (c *regionServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*RegionList, error) {
	out := new(RegionList)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.RegionService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Region, error) {
	out := new(Region)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.RegionService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionServiceServer is the server API for RegionService service.
type RegionServiceServer interface {
	List(context.Context, *ListRequest) (*RegionList, error)
	Get(context.Context, *GetRequest) (*Region, error)
}

// UnimplementedRegionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRegionServiceServer struct {
}

func (*UnimplementedRegionServiceServer) List(ctx context.Context, req *ListRequest) (*RegionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedRegionServiceServer) Get(ctx context.Context, req *GetRequest) (*Region, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterRegionServiceServer(s *grpc.Server, srv RegionServiceServer) {
	s.RegisterService(&_RegionService_serviceDesc, srv)
}

func _RegionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.RegionService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.RegionService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.RegionService",
	HandlerType: (*RegionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RegionService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RegionService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "region.proto",
}
