/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type ListRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	LabelSelector        string   `protobuf:"bytes,2,opt,name=labelSelector,proto3" json:"labelSelector,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Continue             string   `protobuf:"bytes,4,opt,name=continue,proto3" json:"continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ListRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetContinue() string {
	if m != nil {
		return m.Continue
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "kubecarrier.api.v1.GetRequest")
	proto.RegisterType((*ListRequest)(nil), "kubecarrier.api.v1.ListRequest")
}

func init() {
	proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe)
}

var fileDescriptor_7f73548e33e655fe = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbf, 0xcf, 0x82, 0x30,
	0x10, 0x86, 0x53, 0xe0, 0xfb, 0x75, 0x5f, 0x58, 0x2e, 0x0e, 0x8d, 0x13, 0x21, 0x0e, 0x4c, 0x24,
	0xc4, 0xcd, 0xd1, 0xc5, 0xc5, 0x09, 0x37, 0xb7, 0xd2, 0xdc, 0xd0, 0x58, 0x5a, 0x2c, 0x2d, 0xab,
	0xff, 0xba, 0x49, 0x51, 0x22, 0xdb, 0x3d, 0x6f, 0x9e, 0xf7, 0x92, 0x17, 0x72, 0x47, 0xf7, 0x40,
	0xa3, 0xaf, 0x07, 0x67, 0xbd, 0x45, 0xbc, 0x85, 0x8e, 0xa4, 0x70, 0x4e, 0x91, 0xab, 0xc5, 0xa0,
	0xea, 0xa9, 0x29, 0x0f, 0x00, 0x27, 0xf2, 0xed, 0xec, 0x21, 0x42, 0x66, 0x44, 0x4f, 0x9c, 0x15,
	0xac, 0xfa, 0x6b, 0xe3, 0x8d, 0x1c, 0x7e, 0x84, 0x94, 0x36, 0x18, 0xcf, 0x93, 0x18, 0xbf, 0xb1,
	0x7c, 0xc0, 0xff, 0x59, 0x8d, 0x4b, 0xf9, 0x43, 0x64, 0x2b, 0x11, 0x77, 0x90, 0x6b, 0xd1, 0x91,
	0xbe, 0x90, 0x26, 0xe9, 0xad, 0x7b, 0x3d, 0x5a, 0x87, 0xb8, 0x81, 0x2f, 0xad, 0x7a, 0xe5, 0x79,
	0x5a, 0xb0, 0x2a, 0x6d, 0x67, 0xc0, 0x2d, 0xfc, 0x4a, 0x6b, 0xbc, 0x32, 0x81, 0x78, 0x16, 0x6b,
	0x0b, 0x1f, 0xb3, 0x6b, 0x32, 0x35, 0xdd, 0x77, 0x5c, 0xb7, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x09, 0x49, 0x29, 0x9e, 0xee, 0x00, 0x00, 0x00,
}
