/*
Copyright 2020 The KubeCarrier Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	Metadata             *ObjectMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 string      `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Service) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type ServiceList struct {
	Metadata             *ListMeta  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Service `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (m *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(m, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceList) GetItems() []*Service {
	if m != nil {
		return m.Items
	}
	return nil
}

type ServiceGetRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceGetRequest) Reset()         { *m = ServiceGetRequest{} }
func (m *ServiceGetRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceGetRequest) ProtoMessage()    {}
func (*ServiceGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ServiceGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceGetRequest.Unmarshal(m, b)
}
func (m *ServiceGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceGetRequest.Marshal(b, m, deterministic)
}
func (m *ServiceGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceGetRequest.Merge(m, src)
}
func (m *ServiceGetRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceGetRequest.Size(m)
}
func (m *ServiceGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceGetRequest proto.InternalMessageInfo

func (m *ServiceGetRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceGetRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceGetRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type ServiceListRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	LabelSelector        string   `protobuf:"bytes,4,opt,name=labelSelector,proto3" json:"labelSelector,omitempty"`
	Limit                int64    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Continue             string   `protobuf:"bytes,6,opt,name=continue,proto3" json:"continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceListRequest) Reset()         { *m = ServiceListRequest{} }
func (m *ServiceListRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceListRequest) ProtoMessage()    {}
func (*ServiceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ServiceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceListRequest.Unmarshal(m, b)
}
func (m *ServiceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceListRequest.Marshal(b, m, deterministic)
}
func (m *ServiceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceListRequest.Merge(m, src)
}
func (m *ServiceListRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceListRequest.Size(m)
}
func (m *ServiceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceListRequest proto.InternalMessageInfo

func (m *ServiceListRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceListRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceListRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ServiceListRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *ServiceListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ServiceListRequest) GetContinue() string {
	if m != nil {
		return m.Continue
	}
	return ""
}

func init() {
	proto.RegisterType((*Service)(nil), "kubecarrier.api.v1.Service")
	proto.RegisterType((*ServiceList)(nil), "kubecarrier.api.v1.ServiceList")
	proto.RegisterType((*ServiceGetRequest)(nil), "kubecarrier.api.v1.ServiceGetRequest")
	proto.RegisterType((*ServiceListRequest)(nil), "kubecarrier.api.v1.ServiceListRequest")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xed, 0xa4, 0x4d, 0x27, 0xea, 0x81, 0x11, 0x87, 0x95, 0xa9, 0x20, 0xb2, 0x00, 0xe5,
	0xe4, 0x55, 0x52, 0x21, 0xa1, 0xc2, 0xa9, 0x97, 0x5e, 0x40, 0x48, 0xee, 0x09, 0x6e, 0x9b, 0x65,
	0x54, 0x2d, 0x38, 0xbb, 0xc1, 0x3b, 0xf6, 0x81, 0x28, 0x17, 0xce, 0x70, 0xe2, 0x29, 0x78, 0x05,
	0x5e, 0x83, 0x57, 0xe0, 0x41, 0x90, 0xed, 0x6d, 0x49, 0x69, 0x15, 0x24, 0xb8, 0xcd, 0x78, 0xbf,
	0xf9, 0x7e, 0x66, 0xd7, 0x70, 0xe8, 0xa9, 0x6a, 0x8c, 0xa6, 0x7c, 0x55, 0x39, 0x76, 0x88, 0xef,
	0xeb, 0x05, 0x69, 0x55, 0x55, 0x86, 0xaa, 0x5c, 0xad, 0x4c, 0xde, 0xcc, 0xd2, 0xa3, 0x0b, 0xe7,
	0x2e, 0x4a, 0x92, 0x6a, 0x65, 0xa4, 0xb2, 0xd6, 0xb1, 0x62, 0xe3, 0xac, 0xef, 0x27, 0x52, 0x58,
	0x12, 0xab, 0xbe, 0xce, 0x5e, 0xc3, 0xfe, 0x79, 0x4f, 0x87, 0x27, 0x30, 0x6a, 0x0f, 0xde, 0x2a,
	0x56, 0x22, 0x9a, 0x44, 0xd3, 0xf1, 0xfc, 0x7e, 0x7e, 0x93, 0x3b, 0x7f, 0xb5, 0x78, 0x47, 0x9a,
	0x5f, 0x12, 0xab, 0xe2, 0x0a, 0x8f, 0x08, 0x03, 0xbf, 0x22, 0x2d, 0xe2, 0x49, 0x34, 0x3d, 0x28,
	0xba, 0x3a, 0xfb, 0x08, 0xe3, 0x40, 0xfd, 0xc2, 0x78, 0xc6, 0xa7, 0x37, 0xe8, 0x8f, 0x6e, 0xa3,
	0x6f, 0xb1, 0x7f, 0x90, 0xcf, 0x60, 0x68, 0x98, 0x96, 0x5e, 0xc4, 0x93, 0x64, 0x3a, 0x9e, 0xdf,
	0xbb, 0x6d, 0x2c, 0x28, 0x15, 0x3d, 0x32, 0xab, 0xe1, 0x4e, 0xf8, 0x72, 0x46, 0x5c, 0xd0, 0x87,
	0x9a, 0x3c, 0xa3, 0x80, 0xfd, 0xb0, 0xba, 0xce, 0xc0, 0x41, 0x71, 0xd9, 0xb6, 0x27, 0x0d, 0x55,
	0xde, 0x38, 0x1b, 0x12, 0x5c, 0xb6, 0x6d, 0x30, 0xab, 0x96, 0x24, 0x92, 0x3e, 0x58, 0x5b, 0xb7,
	0x68, 0xa5, 0xb5, 0xab, 0x2d, 0x8b, 0x41, 0x8f, 0x0e, 0x6d, 0xf6, 0x3d, 0x02, 0xdc, 0xca, 0xfc,
	0x3f, 0xc2, 0x5b, 0x22, 0xc9, 0x35, 0x11, 0x7c, 0x08, 0x87, 0xa5, 0x5a, 0x50, 0x79, 0x4e, 0x25,
	0x69, 0x76, 0x55, 0x30, 0x71, 0xfd, 0x23, 0xde, 0x85, 0x61, 0x69, 0x96, 0x86, 0xc5, 0x70, 0x12,
	0x4d, 0x93, 0xa2, 0x6f, 0x30, 0x85, 0x91, 0x76, 0x96, 0x8d, 0xad, 0x49, 0xec, 0x75, 0x63, 0x57,
	0xfd, 0xfc, 0x5b, 0x0c, 0xa3, 0x60, 0xde, 0xe3, 0xe7, 0x08, 0x06, 0xdd, 0xb5, 0x3d, 0xde, 0xb1,
	0xed, 0xad, 0x8c, 0xe9, 0x83, 0xbf, 0xe0, 0xb2, 0x67, 0x9f, 0x7e, 0xfc, 0xfc, 0x1a, 0x3f, 0xc1,
	0x63, 0xd9, 0xcc, 0x64, 0xc8, 0xe2, 0xe5, 0x3a, 0x54, 0x1b, 0x19, 0x56, 0xe2, 0xe5, 0x3a, 0x54,
	0x1b, 0xb9, 0x0e, 0xcb, 0xd8, 0xe0, 0x97, 0x08, 0x92, 0x33, 0x62, 0x7c, 0xb4, 0x43, 0xe5, 0xf7,
	0x4d, 0xa7, 0xbb, 0x9e, 0x48, 0x76, 0xda, 0x19, 0x79, 0x8e, 0x27, 0xff, 0x60, 0x44, 0xae, 0xdb,
	0x17, 0xb0, 0x39, 0x1d, 0xbc, 0x89, 0x9b, 0xd9, 0x62, 0xaf, 0xfb, 0x87, 0x8e, 0x7f, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0x11, 0x2e, 0xfd, 0x92, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServicesClient is the client API for Services service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServicesClient interface {
	List(ctx context.Context, in *ServiceListRequest, opts ...grpc.CallOption) (*ServiceList, error)
	Get(ctx context.Context, in *ServiceGetRequest, opts ...grpc.CallOption) (*Service, error)
}

type servicesClient struct {
	cc grpc.ClientConnInterface
}

func NewServicesClient(cc grpc.ClientConnInterface) ServicesClient {
	return &servicesClient{cc}
}

func (c *servicesClient) List(ctx context.Context, in *ServiceListRequest, opts ...grpc.CallOption) (*ServiceList, error) {
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.Services/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) Get(ctx context.Context, in *ServiceGetRequest, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := c.cc.Invoke(ctx, "/kubecarrier.api.v1.Services/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicesServer is the server API for Services service.
type ServicesServer interface {
	List(context.Context, *ServiceListRequest) (*ServiceList, error)
	Get(context.Context, *ServiceGetRequest) (*Service, error)
}

// UnimplementedServicesServer can be embedded to have forward compatible implementations.
type UnimplementedServicesServer struct {
}

func (*UnimplementedServicesServer) List(ctx context.Context, req *ServiceListRequest) (*ServiceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedServicesServer) Get(ctx context.Context, req *ServiceGetRequest) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterServicesServer(s *grpc.Server, srv ServicesServer) {
	s.RegisterService(&_Services_serviceDesc, srv)
}

func _Services_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.Services/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).List(ctx, req.(*ServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubecarrier.api.v1.Services/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).Get(ctx, req.(*ServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Services_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubecarrier.api.v1.Services",
	HandlerType: (*ServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Services_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Services_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
