
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: tenants.catalog.kubecarrier.io
spec:
  group: catalog.kubecarrier.io
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: ""
  validation:
    openAPIV3Schema:
      description: Tenant is the Schema for the tenants API.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TenantSpec defines the desired state of Tenant.
          type: object
        status:
          description: TenantStatus defines the observed state of Tenant.
          properties:
            conditions:
              description: Conditions represents the latest available observations
                of a Tenant's current state.
              items:
                description: TenantCondition contains details for the current condition
                  of this Tenant.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      transits from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message is the human readable message indicating
                      details about last transition.
                    type: string
                  reason:
                    description: Reason is the (brief) reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition, one of ('True',
                      'False', 'Unknown').
                    type: string
                  type:
                    description: Type is the type of the Tenant condition, currently
                      ('Ready').
                    type: string
                required:
                - lastTransitionTime
                - message
                - reason
                - status
                - type
                type: object
              type: array
            namespaceName:
              description: NamespaceName is the name of the namespace that the Tenant
                manages.
              type: string
            observedGeneration:
              description: ObservedGeneration is the most recent generation observed
                for this Tenant by the controller.
              format: int64
              type: integer
            phase:
              description: DEPRECATED. Phase represents the current lifecycle state
                of this object. Consider this field DEPRECATED, it will be removed
                as soon as there is a mechanism to map conditions to strings when
                printing the property. This is only for display purpose, for everything
                else use conditions.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
