
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fake-kubecarrier-io-v1-db
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mdb.kubecarrier.io
  rules:
  - apiGroups:
    - fake.kubecarrier.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - dbs
  sideEffects: NoneOnDryRun
