apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecarrier-operator-manager
  namespace: kubecarrier-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: LOG_LEVEL
              value: "0"
